### ISSUE TITLE
Strange results in registries search

### ISSUE THREAD

**Issue by rempsyc** [CenterForOpenScience/osf.io#10472]
It seems like the new search feature is not working as expected for registries in https://osf.io/registries.

1.	When I use the search feature with the full name of my collaborator with quotes, the relevant registrations do not come up in the search results (I get zero results). When not using quotes, I get many unrelated results.

![zero results_RJV](https://github.com/CenterForOpenScience/osf.io/assets/13123390/09cf2930-2fc8-4ff4-bc03-8459708623b0)

3.	Yet, we have two registrations together (screenshots 2 and 3), and I know there are many more.

![reg1](https://github.com/CenterForOpenScience/osf.io/assets/13123390/224bbbf0-9fd8-4be8-8846-c7f1782e4281)

![reg2](https://github.com/CenterForOpenScience/osf.io/assets/13123390/20a4b1f2-7a62-4b47-a8eb-14f034a5cfcf)

Note that I get a similar result using my own name, even though of course I can access my own registrations reliably by clicking on "My Registrations". The issue is that we cannot access collaborators' registrations through their profile.

Is this a "feature" or a bug?

**Comment by mfraezz** [comment]
Hi again @rempsyc, 

I'm pleased to report that creator names are now searched against by default: your screenshot in `1` now yields [two results](https://osf.io/search?q=%22Robert%20J.%20Vallerand%22&resourceType=Registration%2CRegistrationComponent).

However, it appears that your collaborator in question may have multiple accounts, or rather that the `Contributor` object for him on your shared registrations isn't a confirmed and active user. Unregistered `Contributor`s may have names that differ from what's set on their related `User` object. This is because the first time a Contributor is added with a given name and email, a User is created with both of those fields, but subsequent Contributor additions of the same email with a different name do not update the User object, only affecting what is displayed on the contributed object. 

That is to say, when faceting by creator with your account (another new feature with this release) and filtering on "Robert," the "J." is not displayed in [the results](https://osf.io/search?activeFilters=%5B%7B%22propertyVisibleLabel%22%3A%22Creator%22%2C%22propertyPathKey%22%3A%22creator%22%2C%22label%22%3A%22R%C3%A9mi%20Th%C3%A9riault%22%2C%22value%22%3A%22https%3A%2F%2Fosf.io%2Fw7d23%22%7D%5D&q=Robert&resourceType=Registration%2CRegistrationComponent) because it's absent on the backing User object. This is why only two results are displayed when searching for exact matches (`"quotes"`) on his full name, including the "J." Another [four results](https://osf.io/search?q=%22Robert%20Vallerand%22&resourceType=Registration%2CRegistrationComponent) can be found, including the two you're on, when omitting the `J.` from the exact match query.

If he has any trouble claiming his account, the fine folks monitoring support@osf.io should be able to help.

**Comment by rempsyc** [comment]
Thanks, he didn't have any account until recently, so the preregistrations were made at a time when he did not have an account. I will try to help him claim all these occurrences as many are indeed not claimed yet.
