### ISSUE TITLE
Enhance robots.txt

### ISSUE THREAD

**Issue by sloria** [CenterForOpenScience/osf.io#1141]
ping @JeffSpies @jmcarp @lyndsysimon What should go into this file?

**Comment by nanchen47** [comment]
checked with @sloria the robots.txt has been added but incomplete. Change the title of the issue to enhance the robots.txt.

**Comment by sloria** [comment]
To clarify: the OSF does have a robots.txt . Currently, it allows all robots complete access. This may be what we want anyway. @JeffSpies may have thoughts on this.

**Comment by JeffSpies** [comment]
Looks like both osf.io (allow all) and staging.osf.io (disallow all) are how we want them.

**Comment by sloria** [comment]
@JeffSpies That is how they are currently configured.

Closing the issue.

**Comment by sloria** [comment]
@JeffSpies It might make sense to prevent crawling of API endpoints (`/api/*`)?

**Comment by JeffSpies** [comment]
@brianjgeiger thoughts on this? I think we should go ahead with Steve's suggestion.

**Comment by brianjgeiger** [comment]
I don't have a preformed preference on this, and casual search doesn't reveal any general wisdom. Reasoning about it, it would make sense to have google ignore the api routes, because we don't want them to take people to an api page. If they are smarter about it, then using an api route with the v2 serialization would be super handy for them, because it's a concentrated "everything useful without guessing" sort of thing, but I don't know enough about their current algorithms to know if they would even take advantage of that. So I lean towards excluding those routes.

.:Brian

**Comment by JeffSpies** [comment]
And we'll be serving prerendered content to them any way when Kush/Lyndsy
get their service up. I think that's the right call.

Steve, want to hot fix that in the next chance you get?

J.
