### ISSUE TITLE
[dataverse] Update to Dataverse 4.0

### ISSUE THREAD

**Issue by jmcarp** [CenterForOpenScience/osf.io#1219]
Dataverse 4.0 is slated for release this December: http://roadmap.datascience.iq.harvard.edu/milestones/milestone-roadmap/dataverse/. I haven't reviewed the migration documents extensively (at https://docs.google.com/document/d/11DpdKyp1tagmaJAAzRqQBEZEZ69WOOOYsoqhz8UsfNM/edit), but this will inevitably require some changes on our side. It would be ideal to have our add-on ready before Dataverse 4.0 ships, since the current code will stop working as soon as the new Dataverse release goes to production.
@JeffSpies

**Comment by pdurbin** [comment]
[Dataverse 4.0 is here!](http://datascience.iq.harvard.edu/blog/dataverse-40-here)

Unfortunately there was serious performance-related bug at https://github.com/IQSS/dataverse/issues/2012 I was [chatting with](http://irclog.iq.harvard.edu/dataverse/2015-04-14) @rliebz about. But now it's fixed!

This morning I tried following https://osf.io/getting-started/#dataverse with [my OSF account](https://osf.io/m8hja/) but was having trouble using the Dataverse add-on.

Please let me know when I should try again and if there's anything you need from me! All the latest information is at http://guides.dataverse.org/en/latest/api/sword.html including the biggest backward-incompatible change of disabling auth via username and password in favor of an API token: https://github.com/IQSS/dataverse/issues/1823

p.s. I just added a shout out to @rliebz and @CenterForOpenScience at http://guides.dataverse.org/en/latest/api/client-libraries.html . I was able to run the tests at https://github.com/IQSS/dataverse-client-python (code by @rliebz ) and they all passed. Awesome. :+1:

**Comment by rliebz** [comment]
https://github.com/CenterForOpenScience/osf.io/pull/2426 will resolve this issue, but it is currently under review.

At the moment, our production site should still be linked to https://thedata.harvard.edu, but of course, this means that it is read-only. For an example of a working add-on, feel free to take a look at https://osf.io/hks4q/, but there are a few fixes and improvements still coming with the new PR that do not relate directly to Dataverse 4.0.

**Comment by pdurbin** [comment]
> For an example of a working add-on, feel free to take a look at https://osf.io/hks4q/

I didn't realize that demo of the Dataverse Add-On existed! Neat! But! From what I can tell it's using http://thedata.harvard.edu/dvn/dv/cos/faces/study/StudyPage.xhtml?globalId=doi:10.7910/DVN/26601 which is pretty clearly a demo dataset. We are in the process of deleting this dataset in the production Dataverse 4.0 installation at Harvard ( https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/26601 ) so please touch base with us via support@dataverse.org about setting a demo dataset at https://dataverse-demo.iq.harvard.edu instead (rather than production). Thanks!

Looking forward to #2426 getting merged! Please let me know if there's anything you need!

**Comment by rliebz** [comment]
Resolved by #2426.

**Comment by lbanner** [comment]
Cool -
