### ISSUE TITLE
[feature request] In profile, hit Cancel to exiting edit mode when nothing is changed & Remove the pop up after hitting Cancel.

### ISSUE THREAD

**Issue by huangginny** [CenterForOpenScience/osf.io#1233]
Steps
---------------------
1. Sign in. Hit your name on the top right to go to your profile
2. Hit "Edit"
3. Hit "Cancel" without changing anything

Expected
----------------------
What Facebook or Google+ does: Exits the editing mode

Actual
-----------------------
It does not do anything. User still stays on the editing mode.
To exit the editing mode I have to click "submit," but it does not occur to me when I just want to cancel editing.

Suggestions
------------------------
Honestly, I do not see the "Cancel" button on Github. Also on Facebook, Google+ and other websites, "Save" or "Cancel" would not enable a pop up.
I remembered that we created a "Cancel" button because when we try to navigate away from the page after making some changes without saving, there would be a pop up box saying that "Please save or discard your change." We should provide the "Discard" option.
But then, I am not sure what's the point of having a pop up button to confirm cancellation when you hit the "Cancel" button. It should be the default behavior. Every website does that. You should not hit "Cancel" when you don't want to discard your changes. Also, I know that the pop up box after hitting "Cancel" has already created some messes and confusions. I would say that removing it would save lots of time and make the site much cleaner.

Thoughts? @JeffSpies

**Comment by caneruguz** [comment]
This is an important fix to make, since the default behavior is confusing. I think we should simply remove the Cancel button because:
- We don't seem to have similar Cancel functionality in other form submit situations on the website
- If user leaves without saving changes there is a dialog that will warn them
- Canceling could take them out of profile edit mode but to where? What if in the future they get to this location from different pages? 

Caveat: It looks like exiting page without saving gives dialog box but not in all instances so the fix should check that the box appears for all appropriate changes. 

@GaryKriebel I suggest changing label to Ready with the suggestion above.

**Comment by caneruguz** [comment]
I made some enhancements which are now in staging. Part of the changes include calling Cancel button Discard changes. There is also better navigation between profile information and profile edit pages as they now link to each other. So I recommend closing this issue.

**Comment by lbanner** [comment]
I buy it -- Done!
