### ISSUE TITLE
File page folder order

### ISSUE THREAD

**Issue by chennan47** [CenterForOpenScience/osf.io#1259]
Steps
create a project and then link the project with github repo
then go to the file page

What expected:
the osf storage should appear above the github repo, it is not a good user experience to make user harder to find osf storage file especially when the githu repo has a lot of files in it.

What happened
![screen shot 2014-11-18 at 11 27 50 am](https://cloud.githubusercontent.com/assets/4974056/5091301/f6d7b0de-6f15-11e4-82aa-ca3a257a781d.png)

**Comment by jlcohoon** [comment]
@samanehsan @brianjgeiger is there an update on this?

**Comment by brianjgeiger** [comment]
Waiting on waterbutler and treebeard, although @caneruguz may have done something related to this, I'm not sure.

**Comment by caneruguz** [comment]
These files get ordered in the order that they are put into the JSON object that returns from the API call. In my local installation the OSF Storage is at the very top because it's returned as the first  and I just checked osf.io and OSF storage is the first child there too.

What I think is happening is that hgrid is putting the default list into ALPHABETICAL order while treebeard leaves it alone and displays as they come. All our addons are before O and Components have C. 

If that's what it is, this should be resolved with Treebeard update.

**Comment by caneruguz** [comment]
@GaryKriebel  As far as I can tell this seems to be fixed, in that components appear after OSF-Storage for the parent project. Can we test and update this issue?

**Comment by GaryKriebel** [comment]
While the files within each addon are alphabetized, the addon order does not seem to be what was expected.

![screen shot 2015-07-27 at 2 01 00 pm](https://cloud.githubusercontent.com/assets/9437946/8913633/1c89d808-3468-11e5-9300-6d39917efefb.png)

**Comment by jlcohoon** [comment]
In my experience, things are often alphabetized in terms of when they are
added. So if you add three add-ons, those are sorted alphabetically among
themselves. Then if you add three more those get sorted alphabetically
*separately.*

**Comment by caneruguz** [comment]
Well if we alphabetize OSF storage will not be the first one to show and will not appear above the github as originally pointed out by Nan. 

What is the desired behavior? strict alphabetical? OSF first, then alphabetical? OSF first, then compponents, then alphabetical?

**Comment by caneruguz** [comment]
@nanchen47 can you remove the ready tag from this?

**Comment by GaryKriebel** [comment]
Closed
