### ISSUE TITLE
Project overview scrolls with comment pane

### ISSUE THREAD

**Issue by huangginny** [CenterForOpenScience/osf.io#1321]
This happens both on staging and production. Browser: Chrome 39.0

**Steps**
1. Go to a project and open the comment pane
2. Make sure you have enough comments so that the browser cannot fit all of them. You can also achieve that by shrinking the browser
3. Put your mouse on the overview's page and scroll
4. Put your mouse on the comment pane and scroll

**Expected**
When your mouse is on the overview's page, the comment pane should not scroll, and vice versa.

**Actual**
When you put your mouse on the comment pane, the overview page and the comments are scrolling together
In the meantime, you can see two scrollbars overlapping each other (the right of the image)
![screen shot 2014-12-02 at 1 38 00 pm](https://cloud.githubusercontent.com/assets/8628591/5268551/7b31319e-7a28-11e4-9514-56279b0e3b42.png)

**Comment by nanchen47** [comment]
@samanehsan Is this problem going to be addressed in https://github.com/CenterForOpenScience/osf.io/pull/1762

**Comment by samanehsan** [comment]
This is not resolved by #1762

**Comment by Ghalko** [comment]
What browser is the overlap happening in?
- Chrome: No overlap, when hitting the end of scrolling for comment pane it immediately starts scrolling the main page.
- Firefox: Same as chrome except with a delay between reaching the end of the comment pane and main page scrolling.
- Safari: No overlap, but the scrolling issues are interesting: Initially it is similar to chrome, but if direction is changed it scrolls the last thing to be scrolled first. Sort of like they are using a FILO queue for scrolling rather than a FIFO. But it only does it halfway and half the time.

**Comment by caneruguz** [comment]
I don't think this is an actual bug. 

The way browser behave is that if a container scroll is completed they will move on to parent page scroll, this happens with overflowed divs. In this case once the comment scroll is completed in either direction the scroll continues on the page. The overlap is also normal in this case. 

My opinion is that this is not a fix that is required. Any thoughts @GaryKriebel @lbanner ?

**Comment by lbanner** [comment]
This has some rework in progress in any case, and with your insight @caneruguz, I am closing.
