### ISSUE TITLE
Form feedback does not display next to fields

### ISSUE THREAD

**Issue by sloria** [CenterForOpenScience/osf.io#1392]
## Steps

On any of the forms on the login page, submit any invalid input. 

For example, submit the Register form with no input.

## Expected

Red error messages display under the invalid fields.

This is true on the index page's form:

:+1: 

![osf___home](https://cloud.githubusercontent.com/assets/2379650/5403444/1d79d206-815b-11e4-9530-491497f16cf8.png)

## Actual

Yellow error messages display as growl-like notifications, far away from the input fields. Furthermore, the order of the messages is not the same as the input fields (notice the "email" error is before the "full name" error).

![banners_and_alerts_and_osf___sign_up_or_log_in](https://cloud.githubusercontent.com/assets/2379650/5403468/58adbf54-815b-11e4-8b7e-ebd79a4a47e8.png)

**Comment by lyndsysimon** [comment]
I've wanted to revise the login views for some time, to allow for a drop-down AJAX login on whatever page the user happens to be on. Implementing that would fix this issue as well.

I'm self-assigning because I have a plan in mind to make this happen, but if anyone else wants to do this please feel free to let me know, or just assign yourself to it.

**Comment by nanchen47** [comment]
We don't have the create an account or sign-in page anymore.
