### ISSUE TITLE
[S3] [ui] Confusing button order in S3 addon settings

### ISSUE THREAD

**Issue by caileyfitz** [CenterForOpenScience/osf.io#1399]
An almost repeat of an issue @sloria reported: https://github.com/CenterForOpenScience/osf.io/issues/1045

# Steps
1. Go to a project and enable S3
2. Enter user credentials and press Submit.

# Problem
The "Create Repo" button is closer to the repo selection box than the "Submit" button that saves the selection. This opens potential for user error.
![screen shot 2014-12-15 at 11 11 05 am](https://cloud.githubusercontent.com/assets/5975444/5439121/27e72048-844b-11e4-847c-ccab327a4681.png)

# Potential Solutions
Since this issue was already reported for GitHub by Steve, @kushG has a solution in place (ready to merge) for GH: https://github.com/CenterForOpenScience/osf/pull/1189
![image](https://cloud.githubusercontent.com/assets/5975444/5439196/d1db5c2c-844b-11e4-9ee7-537b8245e8ca.png)

For the sake of consistency, I think that the S3 addon just look the same as the GH addon, so the fix for this should likely mimic the fix for GH.

**Comment by haoyuchen1992** [comment]
I just checked the issue here. I found the current display formats are different now.

#### Now the layout for Amazon S3, it has been updated.
![screen shot 2015-05-28 at 11 58 24 am](https://cloud.githubusercontent.com/assets/5420789/7864627/5836f89c-0531-11e5-99f0-d0f20543fef5.png)

#### However, for the github add-on, it goes back to the the old layout of Amazon S3.
![screen shot 2015-05-28 at 11 57 44 am](https://cloud.githubusercontent.com/assets/5420789/7864600/2a4d462a-0531-11e5-8170-197c6f6a8c25.png)

So are there any other existing decisions which have been made? Is this still a unfixed bug?

**Comment by lbanner** [comment]
I tell you what -- let's defer this in favor of @samchrisinger 's PR here: #2414 ... which I *think* might overcome this issue. Thanks.

**Comment by GaryKriebel** [comment]
Is this the USER settings or the PROJECT settings?  If USER, we should check with @samchrisinger as he has a PR submitted that will update that page.

**Comment by samchrisinger** [comment]
@GaryKriebel. @lbanner this is for project settings, and is outside of the scope of #2414.

**Comment by lbanner** [comment]
Ah -- right -- maybe for next Epic we can bring this into scope .... Thanks.

**Comment by nanchen47** [comment]
As the latest changes done to S3 addon, this is no longer an issue.
![screen shot 2015-08-21 at 3 06 55 pm](https://cloud.githubusercontent.com/assets/11743657/9416908/4ba62382-4816-11e5-88e0-f7a666f57eae.png)
