### ISSUE TITLE
[Presentation Service] Can only navigate to with link

### ISSUE THREAD

**Issue by nicipfeiffer** [CenterForOpenScience/osf.io#1418]
## Steps
1. Search presentations
2. Go to the url https://osf.io/presentations/

## Expected
That if the link is lost to the OSF presentation service that it could be found in another way.

## Actual
The only way to find out about the OSF's presentation service is to know that it exists and have the link to navigate to it.

**Comment by KatyCain526** [comment]
I really think that we should put a link under the "Explore" section of the OSF and potentially in the footer. Both to "Presentation Submission Service" or, if we want to change the name, something like "OSF Posters" (a la f1000posters) or "OSF Presentations" 

I also think that we should do a bit of a re-design of the pages, so that they are all consistent and in the same format. I've put my ideas here: https://docs.google.com/a/cos.io/document/d/1qG6L5e1VL4CmDQsDkrzkgCL4N01bka2dV5ArBbCiQIQ/edit

**Comment by AndrewSallans** [comment]
I like the ideas that Katy outlines here, and agree that more visibility would be good for both discovery and reuse of the content being shared in the events, as well as visibility for the service itself for other potential conference organizers.  Katy's ideas would be a big of work, but would look good.

In the shorter, more immediate term, we might be able to quickly resolve this by adding to the footer (see image here).

![screen shot 2015-01-12 at 2 16 53 pm](https://cloud.githubusercontent.com/assets/2151933/5709212/e9141ed0-9a65-11e4-9e5e-28c52a3e788f.png)

**Comment by brianjgeiger** [comment]
A link in the Explore menu is pretty easy. I've done one already in #1343 and it's a one-line change.

**Comment by lbanner** [comment]
:+1: on @KatyCain526 and @AndrewSallans

**Comment by KatyCain526** [comment]
:+1: @lbanner

**Comment by KatyCain526** [comment]
Okay. So. What are the steps to making these things happen?

**Comment by fabianvf** [comment]
Would we want to index presentation data?

**Comment by KatyCain526** [comment]
Index how? @fabianvf @lbanner 

(trying to keep this conversation going)
