### ISSUE TITLE
[Production] Dataverse: Inconsistent delete function and failure to delete file

### ISSUE THREAD

**Issue by nicipfeiffer** [CenterForOpenScience/osf.io#1475]
## Steps
1. Go to a project with Dataverse linked.
2. Hover over the dataverse file, now hover to the right in the 'actions'  section next to the download button.
3. Click on a dataverse file to go to the files detail page
4. Click on the 'delete' button, submit
5. Return to the files detail page; look for the same file

## Expected
Dataverse files should be consistent from Hgrid to files detail page with the delete function.  IF the delete function is on the the files detail page, then there should also be a delete button action available on the Hgrid files page.
When a user clicks the delete function on the file detail page: the dataverse file is deleted from the file detail page.

## Actual
Dataverse files have inconsistent delete action buttons on the Hgrid and the file detail page.
![screenshot 2015-01-12 21 32 45](https://cloud.githubusercontent.com/assets/9381062/5715189/98791718-9aa2-11e4-9a00-4122c8e2419e.png)
There is no 'x' on hover in the action section to delete a file from the files page Hgrid with dataverse linked files.

![screenshot 2015-01-12 21 34 56](https://cloud.githubusercontent.com/assets/9381062/5715212/ed606132-9aa2-11e4-9ba9-10ac39b04526.png)

Whereas there is a delete button on the files detail page to delete a file.

Receive an 'error: could not delete'
![screenshot 2015-01-12 21 38 54](https://cloud.githubusercontent.com/assets/9381062/5715234/85c09a96-9aa3-11e4-96a5-a19b7bba8531.png)
 DELETE https://osf.io/api/v1/project/e2k9z/dataverse/file/2428419/ 500 (INTERNAL SERVER ERROR)

**Comment by rliebz** [comment]
Because a "Released" version of a Dataverse study is not editable, deletion of files from that version of the study is not possible. To remove a file from the released version of the Dataverse study through the OSF, the closest equivalent action that the Dataverse permits is to go to the "Draft" version of the study, delete the file, re-release the study, and wait for an overnight job to record that the study has been released. While this behavior is probably more intuitive for Dataverse users, I wonder if there is a way that this sort of information could be better communicated to the user.

The fact that a delete button exists on the files detail page is not intended, and I can address that issue.

**Comment by GaryKriebel** [comment]
@rliebz why don't we wrap this into the dataverse updates for the new api

**Comment by rliebz** [comment]
The new API will have some major changes in how our users interact with Dataverse, so it is probably smart not to invest too much in the interface. For now, it might still be a good idea to prevent users from generating a 500.

**Comment by lbanner** [comment]
As you note, @rliebz , Shall we just remove the 'delete' button for the Dataverse Add-on? @GaryKriebel ?

**Comment by rliebz** [comment]
That should be sufficient.

**Comment by GaryKriebel** [comment]
Corrected with the above PR.
