### ISSUE TITLE
BibTeX format in citations

### ISSUE THREAD

**Issue by mbudisic** [CenterForOpenScience/osf.io#1510]
Suggestion: For those of us using LaTeX, it would be nice if various citations formatting, e.g., in Projects, would print a BibTeX format of citation, along with APA, MLA, Chicago, etc.

**Comment by lyndsysimon** [comment]
Not only do I think this is a great idea, I'm actually working on a project now that will do this and more.

I've already got code in development that will allow the user to choose any arbitrary citation format that's currently supported by [CSL (Citation Style Language)](http://citationstyles.org). You can find that repository [here](https://github.com/citation-style-language/styles). BibTeX is supported, as are multiple versions of APA, MLA, and Chicago.

While I can't provide an exact date on when you can expect to see it in production, I can say that it is my primary goal for this quarter, which ends February 28.

If you have the time, you might be able to help me with that by sharing the tools you use for publication. You mentioned that you're using LaTeX - what software do you use to edit your documents? Do you use any citation management tools or applications? How about online services (Zotero, Mendeley, Papers, etc.)

**Comment by mbudisic** [comment]
Excellent, I'm really looking forward to further development of OSF.

I'm glad to provide info: I use Emacs+AUCTeX to edit LaTeX documents, while for bibliography I use Zotero with Better BibTeX plugin to generate .bib files. I used to use Papers as well, but quit b/c I needed something that works across all platforms (Papers did not work on linux at the time... I don't know what current state is). I will likely use WriteLaTeX and/or ShareLaTeX in near future, as they are starting to take hold in math collaborations, but I haven't tried them out yet.

**Comment by wwaites** [comment]
On Fri, 16 Jan 2015 13:54:05 -0800, Lyndsy Simon <notifications@github.com> said:

    > If you have the time, you might be able to help me with that by
    > sharing the tools you use for publication. You mentioned that
    > you're using LaTeX - what software do you use to edit your
    > documents? Do you use any citation management tools or
    > applications? How about online services (Zotero, Mendeley,
    > Papers, etc.)

Lyndsy this is great to hear. Myself I use emacs to edit text and
Zotero to keep references. The main reason for using Zotero is because
it can pull the embedded metadata out of publishers' web pages about
papers. This is much more convenient than making entries by hand or
even cutting and pasting. This feature is why I use Zotero instead of,
say the ebib emacs package.

In fact, though I did suggest to contact@cos.io that BibTeX would be
useful -- and it generally would be -- what is more important for me
is the embedded metadata to save constructing the entry by hand.

Personally I'm not bothered about citation styles as such since there
are zillions of them and it's the job of bibtex/biber to do the
formatting.

Either way, this is very good news!

One idea that we have had for the course where we are trying out OSF
is to collaboratively produce a book with the students. This suggests
that we'll need to solve a different but related problem about
citations -- how to store them and share them through OSF in a
reasonable way that doesn't require specific tools (don't want to
require that they all use Zotero, for example). Any thoughts on how to
approach this would be gratefully received.

Cheers,
-w

**Comment by JeffSpies** [comment]
Hi, W,

Your request via contact@ was logged. Those requests are then reviewed as
we start working on new features. Keep the suggestions coming there or here
on Github.

Can you go into a bit more detail on what you are trying to do? It would be
helpful to understand as we go about architecting how we handle citations.

**Comment by nanchen47** [comment]
@lyndsysimon can you give an update on this issue? Thanks.

**Comment by lyndsysimon** [comment]
Citations are available on the OSF now in a variety of formats, BibTeX included. Closing this issue as complete :)
