### ISSUE TITLE
[production] view-only link shares parent and grandchild component but cannot access grandchild

### ISSUE THREAD

**Issue by saradbowman** [CenterForOpenScience/osf.io#1514]
Behavior: 

Creating a view-only link gives option to share parent ("Test 3") and nested grandchild component ("Component A.1"), without sharing child component ("Component A") in between:
![screen shot 2015-01-17 at 1 07 03 pm](https://cloud.githubusercontent.com/assets/7749914/5789851/c59180a0-9e49-11e4-8962-075680486c4a.png)

However, unless the child component is shared in the view-only link, there is no way to access the grandchild component from the parent component:

![screen shot 2015-01-17 at 1 09 17 pm](https://cloud.githubusercontent.com/assets/7749914/5789856/36dfabba-9e4a-11e4-8e62-f50ffd6bd124.png)

![screen shot 2015-01-17 at 1 09 33 pm](https://cloud.githubusercontent.com/assets/7749914/5789858/3c2dbe9a-9e4a-11e4-84ca-3fa7f1e162d7.png)

Expected:
 
User will be able to access grandchild component and its files as shared in the view-only link.

Proposed Solutions:

-Do not allow combination of Parent + Grandchild component in view-only link/require user to create separate view-only link for grandchild
-Allow private child component to be opened by view-only link holder: don't show title of private component or any of its contents, but allow the link-holder to click "private component" to open it and see relevant nested components

**Comment by lbanner** [comment]
I think a third approach, which might be less complex to implement and simplest to understand: If / when clicking a "grandchild" element to share via the link, by default the "child" component is ticked and shared. Effectively, no sub-element can be shared without sharing the parent element. However, you can choose one or more sub-elements to share.

**Comment by brianjgeiger** [comment]
This is something of a concern in a broader context; after all, you can also have contributors in that state. The main difference is we have mechanisms in place to allow people to access anything they can contribute to, while those mechanisms won't work with private links. Still, in a project, it would be good for the component view to give you the capability to get to anything that you have access to.

Short of redesigning everything, I think my preference would be to only allow the checkboxes to be active on elements that you have checked above, rather than auto-checking things in-between. It means that users have to explicitly choose what they are sharing rather than possibly accidentally sharing something they didn't mean. 

As an additional flourish, it might be worth putting a help item (say a ? with tooltip or similar) that is by any disabled items explaining why they are disabled. In fact, I'd be tempted to replace the checkbox with the question mark when appropriate.

**Comment by brianjgeiger** [comment]
I'm not going to be able to do all of this with front-end only code; I need to add parent information to the get_editable_children view because of the way the data was flattened out.

**Comment by lbanner** [comment]
Who do you need @brianjgeiger --- @jmcarp ? @samchrisinger ?

**Comment by brianjgeiger** [comment]
Nobody, I'm just documenting progress.

**Comment by lbanner** [comment]
OK -- thought maybe you needed some back-end back-up! :smile_cat: -- TY!

**Comment by brianjgeiger** [comment]
Okay, here's the change. PR coming shortly.

![private link grandchildren](https://cloud.githubusercontent.com/assets/6599111/6495825/83e35770-c29b-11e4-973d-a553875195ab.gif)

**Comment by lbanner** [comment]
Cool :octocat:

**Comment by saradbowman** [comment]
+1!
