### ISSUE TITLE
redirect to desired page after login

### ISSUE THREAD

**Issue by saradbowman** [CenterForOpenScience/osf.io#1582]
Behavior: User clicks on link to private resource on the OSF and is instructed she must sign in to view resource. User signs in and is directed to her own dashboard and has to navigate to the resource she was trying to reach in the first place.

Desired behavior: Upon logging in, user is directed to the private resource rather than her dashboard.

**Comment by brianjgeiger** [comment]
That should be what's happening (and I tested it just now and it seemed to be working that way).

It will only work if you sign in on the page that's presented to you when you try to access the resource; if you land on that page then click the sign-in button (which I have done many times) it won't take you to the proper page. Otherwise it will (or seems to according to my testing and how it's supposed to work).

**Comment by JeffSpies** [comment]
@saradbowman can you provide an example (perhaps not exactly the one the user reported but one that adequately mimics the issue?)?

**Comment by saradbowman** [comment]
Actually... no. I didn't realize this was intended behavior, and now I
can't replicate the error on Safari or Chrome. Gathering more information
from the user....

**Comment by HarryRybacki** [comment]
@saradbowman is this still occuring or can we close this issue?

**Comment by saradbowman** [comment]
We can close this out -- we couldn't repeat the error here and the user
reported that it seemed to resolve itself.

**Comment by HarryRybacki** [comment]
pinging @lbanner

**Comment by lbanner** [comment]
Thank you both -- Closing.
