### ISSUE TITLE
Alphabetical file sorting also sorts components/add-ons

### ISSUE THREAD

**Issue by jlcohoon** [CenterForOpenScience/osf.io#1598]
Images are from staging, but the issue is the same on production.
<h4>Steps</h4>
1. Visit a project with multiple components and an add-on (https://staging.osf.io/frzcd/)
2. Note the order of the components on the right
3. Note that the order of the components in the file tree on the left matches the order on the right
![screen shot 2015-01-26 at 3 28 31 pm](https://cloud.githubusercontent.com/assets/4965832/5907831/306d8978-a570-11e4-956f-647a5dd6f63a.png)
4. Click on the sort by name button to make the files sort alphabetically (ascending or descending)

<h4>Expected</h4>
1. Components/Add-ons would stay in their original order
2. Files within each add-on or component would sort alphabetically

<h4>Actual</h4>
1. Components and add-ons are included in the alphabetical sorting. They are sorted by the first letter that is displayed, meaning components like "Component: ZZZ" (starts with a C) is placed before the top-level project's OSF storage (starts with an O). 
![screen shot 2015-01-26 at 4 12 05 pm](https://cloud.githubusercontent.com/assets/4965832/5908501/1e2051aa-a576-11e4-9a4e-4ce6dfc06d11.png)

2. Within each component/add-on folder, files are sorted alphabetically (correctly)

This might be more of a discussion item, but I would prefer that components and other add-ons stay in their position when files are sorted, and just those files within them get alphabetized. This way top-level file storage and add-ons don't get misplaced.

**Comment by lbanner** [comment]
@caneruguz With Treebeard -- What is our intended / expected functionality here? All  files + folders in alphabetical or reverse alphabetical order depending on selection?

**Comment by caneruguz** [comment]
For some reason I didn't get a notification for being tagged in this issue or what's mroe likely it that I archived it with many other github notices coming my way.  I would have addressed this issue before our release otherwise. 

Treebeard is a library so it's rules are very general, the intended behavior is that it applies throughout the entire list. 

However Files page has already many of its own functionality so we can easily add something here that makes the sorting start at a certain depth. It would be very easy to do. 

Can someone assign me to this?

**Comment by lbanner** [comment]
@caneruguz Done!
