### ISSUE TITLE
[production] deselecting add on gives no warning

### ISSUE THREAD

**Issue by saradbowman** [CenterForOpenScience/osf.io#1621]
Steps
-------
1. Configure Github or Dropbox in an project - select add on, create access token, link repo or folder.
2. Remove the add on by unchecking the box in "select add on"
3. Click Submit
4. Add on is removed without displaying a warning

Expected
------------
There would be a warning, as there is on the account settings page when you deactivate an add on this way:

![screen shot 2015-01-27 at 7 52 00 pm](https://cloud.githubusercontent.com/assets/7749914/5930651/5852eab4-a660-11e4-9b7a-745e92c67ff9.png)

Or when you deauthorize in a project: 

![screen shot 2015-01-27 at 8 10 06 pm](https://cloud.githubusercontent.com/assets/7749914/5930666/8d75d562-a660-11e4-850a-0e58f58452ef.png)

Actual
--------
There is no warning. I have tested this with Github and Dropbox in Safari and Chrome.

**Comment by samanehsan** [comment]
I can take this one! @lbanner @GaryKriebel

**Comment by samanehsan** [comment]
Oh wait, nevermind! I didn't see the "discuss" tag.

**Comment by brianjgeiger** [comment]
On the user settings, removing the addon will have potentially unexpected ramifications. You could have 30 projects, and all of those could lose their github stores by clicking one box. I don't know if you lose the github authorization after that or not, but if you do, then there would definitely be lost information.

On the project settings page, it will only affect the project you are on, which is a much simpler change conceptually and I would expect that, if someone unchecks and saves from there, that they really mean it. Also, I think reversing that would only take re-checking the box and saving again, and I think all of the settings would be preserved.

So, if all the things I believe are true are, in fact, true, then I wouldn't think we need the confirmation there.

**Comment by lbanner** [comment]
"if" :smiling_imp: ? Personal app opinion, it is always a good UI approach to offer a warning if a choice has ramifications to function, visibility, etc.

**Comment by brianjgeiger** [comment]
Ehhh, not always. There's a lot of overhead to that. Easily reversed and understood decisions are often easier just to let them reverse. It's essentially the question, do you want to make it half-again as difficult to do the thing every time, no matter what, or just twice as difficult to reverse if you make a mistake. 

On the plus side, this is a function that shouldn't be performed by a user regularly, so the amount of person-hours lost to the extra clicking probably won't matter that much. Most likely, it's five one, half-dozen the other the way it would work out. But philosophically, I lean towards letting people change and fix rather than giving them something to click through, partly because the more of those warnings you get, the less likely people will pay attention to them.

**Comment by lbanner** [comment]
Ah, but you are a developer -- I tend to err on the side of the non-technical user who accidentally clicks a button, gets no message, and then freaks out when what they expected to still be there (like files) are no longer there :scream_cat:

**Comment by brianjgeiger** [comment]
Understood. How frequently does this happen? I know it's an issue from @saradbowman, so is it from a user or something that was just come across. If we have user reports of problems with this, then I'm certainly for it. If it hasn't been an issue, and it's just a matter of telling them to click the button again, then I'm not as for it, because it is a two-step process already. If it were a single click to disable, then absolutely I'd be for it, because a single click is far too easy.

All that being said, I think I'm done clarifying, so whatever the decision from here out works for me.

**Comment by saradbowman** [comment]
I discovered this during testing -- not a report from a user
