### ISSUE TITLE
Search bar on mobile is covered by nav bar

### ISSUE THREAD

**Issue by mckidwell** [CenterForOpenScience/osf.io#1649]
Steps

1. Open osf.io on your mobile browser
2. Click the magnifying glass icon to search

Expected

The search bar will appear underneath the nav bar, so that users can see what they are typing.

Actual

Search bar is covered by the nav bar - it appears that the text "Open Science Framework" is farther down than it should be? Image attached.

![screenshot_2015-01-30-08-14-13](https://cloud.githubusercontent.com/assets/7945215/5976469/46dee7c6-a85c-11e4-833c-1d12cc29f81d.png)

**Comment by brianjgeiger** [comment]
Ah, okay. Safari and mobile safari on my phone don't go that narrow, but the phrase "Open Science Framework" should either disappear entirely or be replaced by "OSF", I think, below a certain width. @caneruguz

**Comment by brianjgeiger** [comment]
Probably be replaced by OSF, as that's what happens during one of the midway-phases of the responsive setup.

**Comment by caneruguz** [comment]
This happens on very narrow devices and unfortunately Bootstrap doesn't have an extra small size. 
The solution to this problem may need to be specific to this one or a site wide introduction of xxs width setting. This would depend on whether anything else needs improvement on this size. Otherwise Brian's solution is the best for this case.

**Comment by caneruguz** [comment]
![unnamed](https://cloud.githubusercontent.com/assets/1314003/6044279/39fbfbfe-ac60-11e4-95b0-4b87cf857f91.png)

This also hides the project navigation. I should fix this now, @lbanner can you assign me to this.

**Comment by lbanner** [comment]
Got it @caneruguz
