### ISSUE TITLE
File Scrollbar Jitter

### ISSUE THREAD

**Issue by macklenc** [CenterForOpenScience/osf.io#1661]
Steps
-------
1. Login
2. Navigate to a project root
3. Grab scroll bar in the "files" box and scroll through content

Expected
------------
Smooth scrolling

Actual
--------
Jittery scrolling. While moving the mouse up and down the scroll bar seems to jump up and down as the mouse moves. I've noticed this issue in both Firefox and Chrome.

**Comment by brianjgeiger** [comment]
In Chrome, but not Firefox nor Safari, I can get https://osf.io/ezcuj/files/ to do a bit of jittering if I scroll all the way to the bottom and, while holding the mouse, move it to the left or right. Then it shakes up and down a pixel or two very rapidly. But nothing particularly noticeable when scrolling up and down.

What's the order of magnitude of files that you're working with? Is it a particularly large grid? Does it happen on the page linked above for you? Thanks!

**Comment by macklenc** [comment]
I can't really get the file list at that link to jitter. I just made my project public, since the scroll bar still jitters for me: https://osf.io/wietn/. There aren't that many files (and even fewer from the public view) in the file list.

**Comment by brianjgeiger** [comment]
For me, I can only get a jitter if I'm moving the cursor left to right or right to left (even if that happens when I'm moving it up and down as well, it seems to be the left-right movement that causes the trouble). Here's a sample below. Can you verify if that seems to be the case for you as well?

![scroll_jitter](https://cloud.githubusercontent.com/assets/6599111/5992382/9b058658-a9f5-11e4-986a-d8928164406d.gif)

**Comment by brianjgeiger** [comment]
@caneruguz, this seems like something you might be interested in.

**Comment by macklenc** [comment]
That is the same jitter I get when I try to move the bar up or down. I just tried side to side and I got the same jitter. Are you using an apple device? I'm not sure if that would make a difference, I've tried two different computers, one running Windows, and one running Linux, and they both give me the jitter going up and down.

**Comment by JeffSpies** [comment]
Hi, Chris,

What mouse are you using?

**Comment by macklenc** [comment]
So far I have used a Logitech G9x, a Logitech M325, and a Synaptics touchpad.

**Comment by caneruguz** [comment]
Thanks for reporting the bug Chris.

I'm able to replicate your bug, it seems like it's only happening when scrolling by dragging the scroll bar itself and in that case only when dragging relatively slowly so that the scroll increment is small. This gives me some information to get started on a fix.

Is that also what's happening on your end?

**Comment by caneruguz** [comment]
I discovered the problem: during dragging the scroll bar with the mouse, the actual mouse position and the drawn scroll position are competing. It's not happening with trackpad because the mouse itself is out of the way or when the mouse is dragged a long way down the refresh is not causing conflict. I think we can resolve this bug very soon.

**Comment by macklenc** [comment]
That is exactly what is happening on my end.

On Sun, Feb 1, 2015 at 6:23 PM, Caner Uguz <notifications@github.com> wrote:

> I discovered the problem: during dragging the scroll bar with the mouse,
> the actual mouse position and the drawn scroll position are competing. It's
> not happening with trackpad because the mouse itself is out of the way or
> when the mouse is dragged a long way down the refresh is not causing
> conflict. I think we can resolve this bug very soon.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CenterForOpenScience/osf.io/issues/1661#issuecomment-72395758>
> .
>



-- 
-Chris

**Comment by sloria** [comment]
@macklenc This has been fixed. Feel free to reopen if the problem persists. Thanks for reporting this.

**Comment by sloria** [comment]
@icereval  reports that this is still happening: http://webmup.com/a62b0/
