### ISSUE TITLE
[staging & production] 'View File' tooltip not visible for long filenames

### ISSUE THREAD

**Issue by caileyfitz** [CenterForOpenScience/osf.io#1678]
Reported by @HarryRybacki on the 0.24 Trello board

# Steps
1. Add a file with a long name 
2. Go to the files page or project overview page and hover over file name

# Expected
It is expected behavior that a tooltip would show and say 'View File' 

# Actual
No tooltip shows on either the files tab or the project overview page
![screen shot 2015-02-02 at 11 44 17 am](https://cloud.githubusercontent.com/assets/5975444/6004452/d93491ea-aad0-11e4-80c7-2eb25280893c.png)

pinging @caneruguz

**Comment by caneruguz** [comment]
@lbanner  I'll take this one as well.

**Comment by caneruguz** [comment]
This issue can be closed now I think it was tested in a prior release.

**Comment by lbanner** [comment]
@caileyfitz -- can you confirm if you would, and we'll close. Thanks.

**Comment by nanchen47** [comment]
@caneruguz It seems this problem still exists on production. It is kinda of different tho.
![screen shot 2015-04-03 at 4 23 42 pm](https://cloud.githubusercontent.com/assets/11743657/6988302/00bd9eba-da1e-11e4-86fd-c668d98bd1fe.png)
![screen shot 2015-04-03 at 4 23 50 pm](https://cloud.githubusercontent.com/assets/11743657/6988305/053deb84-da1e-11e4-9be9-27cbad2383db.png)

on a super long name file, the tooltip show up as white background instead of black and also when you hover the remove icon, the tooltip doesn't show up. 

related issue https://github.com/CenterForOpenScience/osf.io/issues/2394. https://github.com/CenterForOpenScience/osf.io/issues/2352

**Comment by caneruguz** [comment]
I'm having a hard time replicating all these tooltip issues.  Can we provide more details on the context where these issues are happening?

**Comment by nanchen47** [comment]
Just checked on production. Can't repo this problem anymore.
