### ISSUE TITLE
[staging & production] Disable links for non-configured forward add-on in registrations

### ISSUE THREAD

**Issue by caileyfitz** [CenterForOpenScience/osf.io#1684]
# Steps
1. Navigate to a project
2. Go to the settings tab and then Select Add-ons
3. Check the box next to External Link and press Submit
4. Without configuring the link, click the Registrations tab of the project
5. Register the project
6. On the project registration page, find the External Link widget
7. In the message saying the add-on is not properly configured, press the two hyperlinks (one says *settings* and one says *here*)

# Expected
Since this is a registration and thus cannot be altered, these hyperlinks should not be there. Moreover, maybe we should not even show the External Link widget at all since it's not configured in the main project.

# Actual
A configuration error message is shown with hyperlinks. Since there is no Settings tab for registrations, clicking *settings* gives a Bad Request error, and nothing happens when a user presses *here*. 
![image](https://cloud.githubusercontent.com/assets/5975444/6005348/b0bf57ac-aad7-11e4-94e7-78a508531b77.png)

**Comment by lbanner** [comment]
A best solution here might be a warning to the user saying the "add-on is not properly configured" before they are able to leave the page, or, at minimum, create a registration.

**Comment by haoyuchen1992** [comment]
#### I tried to replicated the bug. However, I didn't see the external link panel on the dashboard after I registered the project.  

During the registering process, I selected  "open-ended registration". Since this issue was reported several month ago, is there any change happens here? Why external link panel disappear in dashboard (See picture below) of registered project?

![screen shot 2015-06-16 at 9 56 26 am](https://cloud.githubusercontent.com/assets/5420789/8185143/8ced508e-1410-11e5-9dc2-23b25fbbca19.png)

**Comment by caileyfitz** [comment]
@haoyuchen1992 We no longer register external links, so this is now a non-issue.

**Comment by haoyuchen1992** [comment]
@caileyfitz  OK, got you! So this issue can be closed now. @samanehsan

**Comment by samanehsan** [comment]
Great! Thanks @caileyfitz and @haoyuchen1992!
