### ISSUE TITLE
[discussion] When uploading a new version of a file, whose previous versions had been deleted, the former versions are reborn!

### ISSUE THREAD

**Issue by caileyfitz** [CenterForOpenScience/osf.io#1690]
Reported by @lbanner on the 0.24 Trello board

# Steps
(1) Find a project with a file that has multiple versions
(2) Delete the file: All versions of the file will no longer be visible and should be deleted
(3) Upload the file again, a new file

# Expected
There will be only one version of this new file

# Actual
The former, deleted, version(s) of the file are reborn and accessible again when rendering the file. This is currently expected behavior... but should it be?

**Comment by jlcohoon** [comment]
Like you said, this is expected behavior. I actually think it should remain this way. I've used this feature to get back an old version that I changed my mind about deleting. Furthermore, the point isn't really to hide any old information. If you don't want old versions to come back you just have to use a different file name.

**Comment by lbanner** [comment]
Interesting .... not sure which approach is better!

**Comment by nanchen47** [comment]
@sloria @JeffSpies could you give a direction on this issue?

**Comment by JeffSpies** [comment]
This is actually on this sprint to clarify. I believe Gary has a proposal
put together.

**Comment by GaryKriebel** [comment]
The functionality has been changed and the files no longer come back into the user's directory after uploading a "new" version of the "deleted" file.
