### ISSUE TITLE
[production] 404 page doesn't have search bar sometimes

### ISSUE THREAD

**Issue by fabianvf** [CenterForOpenScience/osf.io#1795]
Steps
-------
1. Go to any non-existent route prefixed with ```osf.io/search```

Expected
------------
You get ```404 Page not found```, but the interface works normally

Actual
--------
You get a ```404``` page, but there is no search bar at the top anymore. Other ```404``` pages behave as expected.

![screen shot 2015-02-13 at 1 44 11 pm](https://cloud.githubusercontent.com/assets/2431974/6193152/70db1f92-b386-11e4-8566-ae46a88263d6.png)
![screen shot 2015-02-13 at 1 43 40 pm](https://cloud.githubusercontent.com/assets/2431974/6193153/70dcc7f2-b386-11e4-8e8c-ce62bbc7f28f.png)
![screen shot 2015-02-13 at 1 43 24 pm](https://cloud.githubusercontent.com/assets/2431974/6193154/70df9b4e-b386-11e4-8b8a-c635301b2a13.png)
![screen shot 2015-02-13 at 1 42 50 pm](https://cloud.githubusercontent.com/assets/2431974/6193155/70e1d8aa-b386-11e4-9248-9c3f8df593bc.png)

**Comment by lbanner** [comment]
Interesting @caneruguz ? @brianjgeiger ?

**Comment by brianjgeiger** [comment]
That makes a certain amount of sense. Anything under osf.io/search/ matches to our search page, which doesn't have a search control at the top of the nav bar, because the search interface is all in the page. However, the 404 page is actually being displayed, not the search page, so we don't get the search content.

We are using javascript to check the location of the page to determine if we want to keep the magnifying glass or no. If we can also add something to see if the page return was a 200 (or maybe something in the 400-500 range), then we could refine the rules a bit.

**Comment by brianjgeiger** [comment]
I don't think we have access to that information directly, so I suspect either we'll need to store something in contextVars, or we will need to do something hacky like check the contents some indication that it's a 404 page.

Orrrr… maybe a better way would be to add to the contextVars a flag "onSearchPage" in search.mako. That way, if the OSF serves up the search page, we don't show the magnifying glass, and if it doesn't, then we don't. That seems like the thing we should have done to begin with, so that is definitely how I would suggest trying to solve it to start.

The relevant function deciding whether we are on the search page is https://github.com/CenterForOpenScience/osf.io/blob/develop/website/static/js/navbarControl.js#L18-L22
