### ISSUE TITLE
[staging & production] Remove Dataverse widget from registrations

### ISSUE THREAD

**Issue by caileyfitz** [CenterForOpenScience/osf.io#1835]
# Steps
1. Navigate to a project
2. Configure Dataverse for that project
3. Register the project
4. View the registration

# Expected
Since a modal pops up saying that Dataverse content cannot be registered, I would expect there to be no Dataverse widget. 

# Actual
The dataverse widget is present with the message "Dataverse add-on is not configured properly." Additionally, the message is shown with hyperlinks. Since there is no Settings tab for registrations, clicking *settings* gives a Bad Request error, and nothing happens when a user presses *here*. 
![screen shot 2015-02-17 at 5 22 23 pm](https://cloud.githubusercontent.com/assets/5975444/6238508/aa2e29ce-b6c9-11e4-82da-e3241c26af42.png)

**Comment by sloria** [comment]
I'm wondering if we should remove the widget--it doesn't do very much, and none of the other storage addons have widgets (if I remember correctly, this widget predates the consolidated Files page). It can also slow down load times of the overview page significantly due to the synchronous request made to Dataverse on the backend . 

Thoughts?

**Comment by JeffSpies** [comment]
Didn't it show the DOI?

**Comment by rliebz** [comment]
The Dataverse team specifically requested that we include that metadata somewhere on a project, which includes the study name (which is available from the files page), doi, Dataverse, and citation information. If it is possible to include that somewhere on the files page, I don't see a reason why it has to be a widget.

**Comment by brianjgeiger** [comment]
I am pro leaving the widget on projects and removing the widget from registrations. It's behaving poorly on registrations, is a simple fix just focusing on that, and if we have the capability to change how we do the metadata display, we can do that with the Dataverse 4.0 upgrade.

**Comment by nanchen47** [comment]
@rliebz will the Dataverse 4.0 upgrade address the problem? Can you provide updates on this one?

**Comment by rliebz** [comment]
No, Dataverse 4.0 will not affect the widget.

The widget updates with metadata pulled from their API as it is rendered on the page. I think the ideal behavior would be that when a project with the Dataverse widget is registered, that information is saved to the registration so that we can guarantee the state of the widget. Removing the widget completely from registrations also seems like a viable option, although we probably should never show the widget if the add-on is does not have valid credentials or a valid dataset.

**Comment by chennan47** [comment]
@samchrisinger does the registration change you made will solve this?

**Comment by nanchen47** [comment]
The dataverse widget is removed on registration project.
