### ISSUE TITLE
Piwik error for some project statistics pages

### ISSUE THREAD

**Issue by abought** [CenterForOpenScience/osf.io#1862]
### Summary
While browsing OSF pages, statistics pages usually display correctly, but reproducibly fail for some projects.

For several projects, going to the statistics tab yields an iframe with an error message from the piwik API. I received this error message reproducibly in multiple attempts 12+ hours apart, using two different browsers.

### Sample pages demonstrating error
https://osf.io/4znzp/statistics/ - project created May 2012
https://osf.io/yz3xu/statistics/ - project created Oct 2014

### Error message
> The requested website idSite is not found in the request, or is invalid. Please check that you are logged in Piwik and have permission to access the specified website.

![screen shot 2015-02-21 at 1 37 01 pm](https://cloud.githubusercontent.com/assets/2957073/6315406/d3fdc4be-b9ce-11e4-8358-2c1aafb16b68.png)

### Piwik request data
The address of the embedded piwik iFrame is given for the two example cases:

https://osf.io/piwik/index.php?module=Widgetize&action=iframe&moduleToWidgetize=Dashboard&actionToWidgetize=index&idSite=342&period=day&date=today&disableLink=1&token_auth=anonymous

https://osf.io/piwik/index.php?module=Widgetize&action=iframe&moduleToWidgetize=Dashboard&actionToWidgetize=index&idSite=16289&period=day&date=today&disableLink=1&token_auth=anonymous

### Other information
I did not see a clear trend on which projects worked/didn't based on project age, creation date, or activity. Valid statistics pages exist for projects whose piwik `idSite` value lies between the two failure cases. (Example of project with valid statistics: https://osf.io/tvyxz/statistics/ , created Feb 2013 )

**Comment by GaryKriebel** [comment]
@lyndsysimon - do you take the pwik issues?

**Comment by lyndsysimon** [comment]
My apologies for the relative silence on this issue - we're coming up on a release, and while we addressed this a few days ago I was only just able to go back and verify that the solution was complete.

The issue at hand was actually resolved last October, as a result of issue #964. In short, duplicating projects via forking, registering, or templating could in some cases result in multiple projects which shared a Piwik site (the `idSite` in the URIs you posted above).

There was a script written to fix the projects that had their Piwik sites improperly set at that time. Unfortunately, looking back through our logs it appears it was not run. As a result, there were many projects created prior to October 2014 which shared Piwik sites.

Whenever a project's permissions are modified, permissions in Piwik site are also set; where projects incorrectly shared a Piwik site with other projects, this resulted in several cases where Piwik sites were erroneously marked as private. This mismatch between the project's privacy settings and the corresponding Piwik site's privacy settings are what caused the errors you reported.

We've now run the script and verified that no projects share Piwik sites - and are in the process of putting in place additional controls to alert us if this situation should arise again.

There are a few instances remaining where a public project's corresponding Piwik site is not set to be publicly viewable. To avoid flooding the Piwik server with update requests, we will be addressing those over the next few days. I'll keep this issue open until this process has been completed. Until then, you can trigger this update manually on any public project for which you are a contributor by toggling it to private, then back to public.

Thanks very much for your accurate and detailed report - it allowed me to quickly rule out a regression and discover that the migration was not run when the fix was originally put in place. If you come across any other issues, please don't hesitate to report them here.

**Comment by abought** [comment]
Thanks for the helpful and informative response, @lyndsysimon : having a clear record of the cause will help track this issue down if there is a regression in the future. Having dealt with partial migrations in the past, I can appreciate the potential for headaches.

So far, I can confirm that one of the sites is now displaying correctly, but the [other](https://osf.io/4znzp/statistics/) is still giving a Piwik error; I assume that the migration script hasn't gotten there yet. I'll check back in ~ 1wk as a followup.

**Comment by lbanner** [comment]
@lyndsysimon Let's knock this one out today. I think @sloria had noted this via email-thread. Thank you @abought for following up.

**Comment by lyndsysimon** [comment]
The migration script completed this morning, and all projects should now be up to date. I've checked the other project you linked above, and verified that it was included in the update.

If you encounter any other issues with Piwik, let us know! :+1:
