### ISSUE TITLE
Download count on pdf not accurate

### ISSUE THREAD

**Issue by jlcohoon** [CenterForOpenScience/osf.io#1883]
<h4>Steps</h4>
1. I downloaded then deleted two files ("mlewis_sfn13.pdf" and "mlewis_thesis.pdf") from two separate components within this project: https://osf.io/muvl6/
2. I deleted the two, now empty, components
3. I uploaded the downloaded versions of those files to the project (https://osf.io/muvl6/) on the files overview page
4. I visited each file's details page

<h4>Outcome</h4>
1. When uploading the files on the files overview page, the new uploads (no previous versions within that project) listed 33 and 32 downloads each.
![screen shot 2015-02-25 at 2 05 48 pm](https://cloud.githubusercontent.com/assets/4965832/6378477/a88d87b4-bcf9-11e4-8100-778ea31f1260.png)

2. When visiting the files' details pages, the file with 33 downloads on the overview still reported 33 downloads. The file that had 32 downloads on the overview page only had 11 listed on the details page. 
![screen shot 2015-02-25 at 2 05 57 pm](https://cloud.githubusercontent.com/assets/4965832/6378483/af137418-bcf9-11e4-9874-ebe1fb1973a6.png)

3. Neither file had previous versions listed in the history. 

<h4>Expected outcome</h4>
1. As both files are new to that project, the download counts should be 0 on both the details page and the overview.
2. Download counts should be consistent between the details page and the overview.

**Comment by lbanner** [comment]
@jmcarp -- Waterbutler? Files don't have individualized records per project?

**Comment by dromero23** [comment]
@jlcohoon Also if you change the name of "pre data collection report hajcak.pdf" to a previous uploaded version such as "mlewis_thesis.pdf" it keeps the same previous count of "mlewis_thesis.pdf"

**Comment by trevinovnc** [comment]
I second what @dromero23 is saying, as well as add in that if you were to update the name of any of your upload files with a different name (eg. change lewis_thesis.pdf to lewis_thesis_v2.pdf) the download count is reset to 0.

**Comment by lbanner** [comment]
Thank you @trevinovnc  -- We'll look into this one.

**Comment by jmcarp** [comment]
Will look at this today.

**Comment by jmcarp** [comment]
This report wound up including a few different issues, some of which are related to communication and one of which is actually a bug.

1. Download counts are grouped by name and don't clear on deleting a file. This is a behavioral issue and not strictly a bug. In general, when a user creates a thing, deletes it, and creates another thing with the same name, OSF treats those things as versions of the same entity. This is the current behavior with wiki pages and files in OSF Storage. So the behavior of download counts is consistent with other analogous features elsewhere in OSF. This behavior might change in the near future, but if it does, it should be changed for all relevant parts of OSF (wiki pages, file versions, and file download counts) so that the system stays consistent. I recommend deferring this pending broader discussion.

2. The files that @jlcohoon pointed out seem to have inflated download counts. This is actually another manifestation of issue 1. It turns out that someone had uploaded files of the same name to that project a long time ago, downloaded them, and then deleted them. So when @jlcohoon uploaded files with the same name, the download counts continued from where they left off instead of starting from zero. I think this should be deferred as well, since it's actually the same issue as above, and should be discussed before we change the code.

3. @jlcohoon also found inconsistent download counts between the files page and the file detail pages. This one's actually a bug that seems to affect a small number of old files. This is separate from the other issues here, so I'm going to re-file it on its own and propose a fix in the new issue.

@lbanner, I'd like to close this issue in favor of #2015.

**Comment by lbanner** [comment]
Got it @jmcarp -- Deferring but not closing this one to deal with the discussable issues above. Noting #2015 as the bug fix. TY

**Comment by nanchen47** [comment]
Close this in favor of #2015.
