### ISSUE TITLE
[bug][ui] Project/component pane can block Sharing and Settings nav items

### ISSUE THREAD

**Issue by HarryRybacki** [CenterForOpenScience/osf.io#1950]
## Steps
1. Go to a project/component with a somewhat lengthy title
2. Click and expand the comment pane
3. Attempt to navigate to the project/component's *Sharing* or *Settings* page

## Expected
User can click either link and be redirected 

## Actual
The links are activated when the mouse hovers over them

## Possible Cause
I believe this has to do with the comment pane, perhaps the div is expanding above it's visual representation and in essence 'covering' the links.

## Note
This is only an issue for project/components with non-short titles

**Hover not working**
![screen shot 2015-02-27 at 11 15 24 am 2](https://cloud.githubusercontent.com/assets/2614670/6416217/8691bec6-be72-11e4-8e3f-8f4dba11994d.png)

**Hover working on non-covered portion**
![screen shot 2015-02-27 at 11 15 22 am 2](https://cloud.githubusercontent.com/assets/2614670/6416239/aff6dc7e-be72-11e4-82d9-7cc7f952848f.png)

**Comment by sambrady3** [comment]
Changing the z-index of the commentPane div to 98 (from 999) fixes the problem. However, updating commentpane.css doesn't immediately solve the problem because the page is actually getting its css from the project-dashboard.js file that webpack builds (using commentpane.css). I don't really know anything about how webpack works, or how/when it builds the project-dashboard.js file, so someone else should probably handle this (and perhaps enlighten me!).

**Comment by lbanner** [comment]
Thank you for taking a look @sambrady3 !

**Comment by lbanner** [comment]
@caneruguz  -- Can you follow up when you get a chance? TY

**Comment by caneruguz** [comment]
Hi @sambrady3 
Thanks for the suggestion, that did indeed solve the problem. 

For further information about what was going on there. Webpack builds javascript across the website into some key combined js files which are then used by the website. Something like this appears:

![screen shot 2015-03-04 at 2 04 11 pm](https://cloud.githubusercontent.com/assets/1314003/6490894/80a7ae72-c277-11e4-8c59-a2d2f34d55c4.png)

Since the website is not using the actual js files, if any change happens they need to be rebuilt. We have a listener for development environment that automatically does this. 

The reason this also applies to CSS is that we are now using webpack to do the same with CSS files (the css is in fact inside the built js file, so you won't see separate css files). So if you make changes to the css files you will need to run webpack again to build the final files. 

Let me know if you have other questions.

**Comment by caneruguz** [comment]
This looks fixed, @lbanner can you review whether this can be closed?

**Comment by lbanner** [comment]
I'll confirm - Thanks!
