### ISSUE TITLE
Wiki very slow with lots of text

### ISSUE THREAD

**Issue by sloria** [CenterForOpenScience/osf.io#2053]
Found by @erinspace: editing text in the wiki can be very slow with a large amount of text. It is worse when the preview pane is up.

**Comment by lbanner** [comment]
@brianjgeiger ? TY

**Comment by brianjgeiger** [comment]
Since it's happening when preview is off as well, it might be related to the collaborative wiki. But yes, we need to check and see what's happening here.

**Comment by fabianvf** [comment]
Saving the wiki also gets really slow as the size increases, not sure if it's related or not

**Comment by brianjgeiger** [comment]
@fabianvf can you link me to a slow wiki page?

**Comment by fabianvf** [comment]
https://osf.io/wur56/wiki/scrAPI/

**Comment by brianjgeiger** [comment]
I believe @erinspace has reported that this issue is fixed, yes?

**Comment by erinspace** [comment]
@brianjgeiger  Yup, seems fixed as I don't see the same lagging that I did before, even with the live view. Looks good from my perspective!

**Comment by JeffSpies** [comment]
@brianjgeiger <https://github.com/brianjgeiger> How was it fixed?

**Comment by brianjgeiger** [comment]
It was caused by the highlighting. They had lots of code snippets on the page. I turned off the highlight rendering for the quick render. There are potentially other optimization a that can be made, as there are some open questions as to why it was a problem even after the view panel was closed.

**Comment by brianjgeiger** [comment]
What I suspect was happening based on the profiling I did is that trying to do multiple renders of the same material in quick succession was causing script to pile up with highlight events, and after that it started thrashing. Ultimately, it might be a better thing to see if we can throttle the math rendering so that it only runs after it has completed (right now we are just debouncing based on keypresses and buffer time). That should prevent this problem from happening with arbitrarily large amounts of wiki data. But I don't know if the amount of effort is really worth it.
