### ISSUE TITLE
New permission default for adding new contributors.

### ISSUE THREAD

**Issue by Ghalko** [CenterForOpenScience/osf.io#2209]
Steps
-------
1. Go to "sharing" tab on project, click add button
2. find and add contributors

Expected
------------
Default permission is not admin.

Actual
--------
Default is admin.

Suggestion
--------
Set to read, read+write, or blank making the admin adding contributors pick one of the permissions options themselves.

I would like to discuss this.

**Comment by brianjgeiger** [comment]
I think 'read' is the most sane default. We could do 'no default' but that just seems like more work. Read will never be disastrous, and could save some clicking, but people do still need to pay some attention with it otherwise they'll have to change it.

Of course, if we were to make the contributor tab changes happen immediately rather than having to submit them in a batch, it would be an equivalent amount of work to just add people and then change their permissions on the contributors tab.

**Comment by fabianvf** [comment]
:+1: for read as the default - better to ask [for] permission[s] than forgiveness

**Comment by Ghalko** [comment]
Talking with Jeff, if default is Read. Then we should think about "request write access" that a read only person can send to the admin.

**Comment by brianjgeiger** [comment]
This would be great if non-contributors could also request access in a read/write/admin capacity. This is a user complaint that I've heard that makes it difficult for people administering the project. They have to do a lot of work to find the right user, which would go away with this mechanism.
