### ISSUE TITLE
[staging & production] Cannot upload files to pre-existing Dataverse datasets

### ISSUE THREAD

**Issue by caileyfitz** [CenterForOpenScience/osf.io#2224]
# Steps
1. Go to a project where Dataverse is configured
2. Go to the files tab
3. Change the version from 'Released' to 'Draft'
4. Try to upload a file

# Expected
The file uploads.

# Actual
The user receives an error saying that the file cannot be uploaded: 
![screen shot 2015-03-18 at 10 00 16 am](https://cloud.githubusercontent.com/assets/5975444/6710441/17cca14c-cd57-11e4-8f7f-c7c5beb44e2c.png)
and a 500 error is shown in the console
![screen shot 2015-03-18 at 10 03 57 am](https://cloud.githubusercontent.com/assets/5975444/6710443/210b5faa-cd57-11e4-94ac-48e83de32d4d.png)

**Comment by rliebz** [comment]
Working from develop, I am still unable to upload files but instead producing a 400. From that, the issue appears to be an issue with the Dataverse server, as a well-formatted `curl` using the Dataverse API is returning a 500 and a Java traceback. It may currently not be possible to upload files using their API.

**Comment by rliebz** [comment]
This issue should now be resolved.

**Comment by caileyfitz** [comment]
Hey @rliebz I have tried uploading multiple files to Dataverse via OSF. I have gotten back a few different types of responses:

- Successful uploads (pdfs, smaller images and docx documents)
- 504 Gateway Timeout for an image (1.1 MB)
- 502 Bad Gateway for a docx file and a larger image (6.6 MB and 1.4 MB, respectively)

**Comment by rliebz** [comment]
Is it reliably rejecting certain files, or failing probabilistically? If you have any files that can reliably produce an error, send them my way and I'll see what I can figure out.

**Comment by caileyfitz** [comment]
It's sort of random. Now docx files are uploading but some video files aren't (gif and some mov files). :imp:

**Comment by sloria** [comment]
@caileyfitz or @nicipfeiffer : Can you check if this is working now?

**Comment by caileyfitz** [comment]
@sloria This is still not working for me. After over a minute of waiting for each file, I get one of two errors: 
![screen shot 2015-03-27 at 11 50 37 am](https://cloud.githubusercontent.com/assets/5975444/6871283/e8e2340a-d477-11e4-91e7-e0d776001c0d.png)
or 
![screen shot 2015-03-27 at 11 51 53 am](https://cloud.githubusercontent.com/assets/5975444/6871286/ec5d851c-d477-11e4-804f-5f53bd42fd73.png)

**Comment by sloria** [comment]
@rliebz Any update from the Dataverse folks about this?

**Comment by rliebz** [comment]
I have replicated the 504 with an MOV file on production that successfully uploads on the dataverse 4.0 feature branch with WaterButler. I'm not sure if this was an issue with the implementation of the python client, the OSF, or an issue on Dataverse, but it should be resolved with the new Dataverse release April 13th. 

I haven't been able to replicate the 502, so I'm not sure if that issue will be resolved as well. @caileyfitz if you have a file that consistently produces that error, I would be happy to take a look at the issue.

**Comment by caileyfitz** [comment]
@rliebz I can't get the 502 consistently :disappointed:

**Comment by rliebz** [comment]
With the release of Dataverse 4.0, it would be worth taking a look to see if this is still an issue. I have not yet run into this while testing 4.0 functionality.

**Comment by lbanner** [comment]
@caileyfitz Can you try to replicate this? If all seems well now, we can close. Thanks.

**Comment by caileyfitz** [comment]
@lbanner I can't try this because there is no horizontal scroll for the files grid and my Dataverse name is too long so I can't switch from Released to Draft :cry:

**Comment by rliebz** [comment]
@caileyfitz Not sure if this helps, but you can resize the columns by dragging the lines in the title bar.
![screen shot 2015-04-21 at 9 47 38 am](https://cloud.githubusercontent.com/assets/5321575/7253555/9ac4f9d6-e80b-11e4-9340-c0e595d7d1a2.png)

**Comment by caileyfitz** [comment]
@rliebz My title is still too long :sob: 
![screen shot 2015-04-21 at 9 50 00 am](https://cloud.githubusercontent.com/assets/5975444/7253591/d39c5452-e80b-11e4-9864-d2189d9cee1e.png)

**Comment by caileyfitz** [comment]
@rliebz @sloria @lbanner I am again not able to upload a file to Dataverse but am getting a 400 Bad Request.
![screen shot 2015-04-21 at 10 46 50 am](https://cloud.githubusercontent.com/assets/5975444/7254893/be271514-e813-11e4-8c56-ea72d82fd8d5.png)

**Comment by lbanner** [comment]
Hmmmm ... Dataverse issue or us?

**Comment by rliebz** [comment]
Dataverse. This issue is occurring for pre-existing datasets that do not meet metadata requirements for 4.0. I've filed an issue at https://github.com/IQSS/dataverse/issues/2062, although I'm not sure how easy this will be to resolve.

Two potential solutions if Dataverse does not resolve the issue quickly:
 1. When connecting a dataset, we warn the users and let them know the solution so they can fix it manually on dataverse.harvard.edu.
 2 . When connecting a dataset, we programmatically fix this by checking the metadata, adding in their OSF email as a contact email on the Dataverse if they are missing one, and add in "Other" as the subject if they are missing one. Probably a bad idea to pass emails along like that, but it does open up the ability to perform a migration for users.

**Comment by lbanner** [comment]
OK -- going to Defer for now -- @rliebz let's keep up-to-date on resolution (or not) from Dataverse.

**Comment by GaryKriebel** [comment]
@rliebz is this still occurring?

**Comment by rliebz** [comment]
As far as I know, this issue as not been resolved. 

Two potential solutions going forward:
 - On the resolution of IQSS/dataverse#2062, we should no longer run into upload issues, and this issue can be closed.
 - On the resolution of https://github.com/IQSS/dataverse/issues/2102, we can manually edit the Dataverse metadata to include the fields necessary that this wouldn't occur, although I hope that the solution to IQSS/dataverse#2062 would make this solution unnecessary. It also comes with the downside of sometimes having to pass an email along to Dataverse, since the two potentially missing metadata fields are email and subject. 

Either way, I don't think there is anything we can do to resolve the problem at this time.

**Comment by caileyfitz** [comment]
Just tried again and got a 503 error!
![screen shot 2015-08-04 at 4 12 26 pm](https://cloud.githubusercontent.com/assets/5975444/9071469/86767ddc-3ac3-11e5-872d-841e67505678.png)

**Comment by GaryKriebel** [comment]
Closed
