### ISSUE TITLE
Downloads are not visible

### ISSUE THREAD

**Issue by TimErrington** [CenterForOpenScience/osf.io#2321]
The downloads for projects are all 0. Here's a screen shot from the APS 2014 presentation service that has multiple downloads associated with them.
![screen shot 2015-03-26 at 10 33 43 am](https://cloud.githubusercontent.com/assets/5816601/6848453/b609b442-d3a3-11e4-8cd4-eb5397af14bd.png)

**Comment by lbanner** [comment]
Let's get someone on this 'cause we want Presentations to look/work right! ... I'd generally go to Josh, however .... @sloria @icereval @JeffSpies -- thoughts on Dev?

**Comment by TimErrington** [comment]
This is also happening on all projects as well. So it doesn't seem to be limited just to presentations.

**Comment by brianjgeiger** [comment]
@chrisseto and @icereval are working on this.

**Comment by lbanner** [comment]
Great -- appreciate the quick pickup.

**Comment by sloria** [comment]
Ok, the download counts should be back.

We found that the root of the problem was the change made in https://github.com/CenterForOpenScience/osf.io/commit/adc2712c3089dd996422dd521d1596dc9f1fb69b, which inadvertently caused counts to reset for files with `.` or `$` characters. We are looking into a more permanent solution for https://github.com/CenterForOpenScience/osf.io/issues/2281 now.
