### ISSUE TITLE
[Staging & Production] SHARE: figshare publications links incorrect

### ISSUE THREAD

**Issue by nicipfeiffer** [CenterForOpenScience/osf.io#2329]
## Steps
1. Go to https://staging.osf.io/share/
2. Search for something
3. Filter your results to only show figshare results
4. Click on the title of a figshare publication

## Expected
The user would be taken to the figshare site and have the publication rendered

## Actual
The user sees 
![screen shot 2015-03-26 at 1 39 32 pm](https://cloud.githubusercontent.com/assets/9381062/6853508/04d55e28-d3c2-11e4-9205-9a62ed1a963b.png)

**Comment by lbanner** [comment]
@fabianvf @chrisseto @erinspace ? -- I did replicate on Production - Thanks.

**Comment by erinspace** [comment]
Right - this is actually how the figshare API works - each url entry in their bulk API links to a separate data blob with much more detailed information. We considered querying a separate time for each entry to get this more detailed information - including the URL to the actual figshare resource - but decided against it because there are so many many many figshare resources per day.

There might be a workaround to show something more elegant based on the information we get from the initial API call - will look into this!

**Comment by lbanner** [comment]
A'ight -- 'cause that's not very pretty :see_no_evil: -- TY

**Comment by chrisseto** [comment]
@erinspace We could link to the doi

**Comment by brianjgeiger** [comment]
Might be worth sending a message to our Figshare contact. I think the SHARE service would be of most use to them if they provided the figshare_url in the initial results.

**Comment by lbanner** [comment]
This was correct, I believe -- I will close.
