### ISSUE TITLE
[staging & production] TOC scrolls in wiki widget on project overview page incorrect for all cases

### ISSUE THREAD

**Issue by caileyfitz** [CenterForOpenScience/osf.io#2348]
## Steps

Case 1 - Projects:

1. Log into OSF on staging
2. Go to https://staging.osf.io/zvecb/
3. Go to the project overview page, the wiki widget.
4. Click each heading in the table of contents and check that the page scrolls to right above each heading
5. Click a heading that is truncated by the widget (ie: click 'CLICK ME' or anything below that)

Case 2 - Private View-only Link: 

1. Go to https://staging.osf.io/v3t7s/?view_only=affe99de07e74ae2b282518719106b1a (a private view-only link)
2. Go to the project overview page, the wiki widget.
3. Click each heading in the table of contents and check that the page scrolls to right above each heading.

## Expected

It is expected that clicking on the heading in the table of contents on the project overview page in both cases pages should make the page scroll right above each heading.

## Actual

The page scrolls to below the heading cutting it off. Additionally, for headings that are truncated by the widget, clicking the headers in the table of contents does not result in a page scroll, although the URL does change to include the heading title.

**Comment by caileyfitz** [comment]
@lbanner I just realized that I never put a title on this! Just confirmed that this is still an issue on staging and production.

**Comment by lbanner** [comment]
Misaligned anchors or the like @brianjgeiger ?

**Comment by brianjgeiger** [comment]
I think for some cases, it's just that it's going down a bit too far. For stuff farther down on the page, it's not properly linking because the content isn't actually on the page.

I think the ideal solution would be to have a parameter that we could pass to the markdown plugin to tell it to send pages to a related URL, then have the TOC links take you to the full wiki page. Aside from modifying the widget, we'd want to make a markdown instance for the project summary page that is different from either of the ones used by the full wiki page. This way, we'd have control over what we do and don't allow to happen on the page.

Alternately, if we had the alternate markdown instance, we could have it strip out references to the TOC rather than showing the TOC. Or we could remove the TOC from the data going into the page before it's passed to the TOC widget. This will only be exacerbated by the fix for #2055, incidentally, if someone sets up a TOC high-up on the page and that's the only thing visible on the preview widget.

**Comment by caneruguz** [comment]
@lbanner I sent a PR related to this issue.

**Comment by nanchen47** [comment]
This pr has been merged and deployed on production.
