### ISSUE TITLE
File rendered overlaps

### ISSUE THREAD

**Issue by AndrewSallans** [CenterForOpenScience/osf.io#2382]
What you did (step by step)
* Went to this page:  https://osf.io/ibdv8/
![screen shot 2015-04-02 at 8 51 14 am](https://cloud.githubusercontent.com/assets/2151933/6964264/7245c01c-d915-11e4-8e54-a75d71c2c3bf.png)

What you expected
* Should resize, wrap, or something to not overlap

What actually happened
* Overlapped

Potential causes
* Not sure

Suggest a solution
* Will not overlap

**Comment by brianjgeiger** [comment]
Is there a general solution we can use for these problems? Because they keep coming up. I know the general problem is that some renderers require a width to be set explicitly and similar. It would be great if we could have a div container that all the plugins could use as a width bound. Would that require a big MFR refactor?

**Comment by nanchen47** [comment]
This is the duplicate issue as https://github.com/CenterForOpenScience/osf.io/issues/2254.
