### ISSUE TITLE
[Production & Staging] Deleting a component gives link to a Forbidden Resource in the Project log

### ISSUE THREAD

**Issue by nicipfeiffer** [CenterForOpenScience/osf.io#2628]
## Steps
1. Go to a project you have admin privileges on
2. Create a new component, name it 'wifi'
3. Change the name of the component to 'new'
4. Go to the settings tab for the component
5. Click to delete the component
6. Go to the parent project and look at the project log

## Expected
There would not be a link to a deleted resource
![screenshot 2015-05-04 21 44 43](https://cloud.githubusercontent.com/assets/9381062/7465872/ff0ec19c-f2a6-11e4-8835-d690ab02037e.png)

## Actual
In the project log the deleted component is listed (should be), but it is listed as a link.  When the user clicks on the link it takes them to a Deleted Resource page.
![screenshot 2015-05-04 21 45 48](https://cloud.githubusercontent.com/assets/9381062/7465869/f817b8a8-f2a6-11e4-88ed-37dc4057cbac.png)

Also, the project log does not list the events in the correct order and doesn't really make any sense.
![screenshot 2015-05-04 21 50 19](https://cloud.githubusercontent.com/assets/9381062/7465906/9bb250e0-f2a7-11e4-8e18-6377cf1783cd.png)
It replaces the name in the log for the project once the name has been changed.
Where is says "Nicole Pfeiffer changed the title from Wifi to project new", maybe it could say "NP changed the title of the project from Wifi to New"...?

**Comment by chennan47** [comment]
Since the log is saved before the nodes is deleted, the previous log contains the component name are supposed not to change with action after the log's action itself. And since the component is deleted, the url are supposed to link you to a 404. In order to remove the link of the previous link requires a search inside the database for all logs related with that node and change all of them. There is no code in OSF currently do that. Not sure if this is a priority to do. @lbanner @GaryKriebel @sloria thought?

**Comment by lbanner** [comment]
Yeah -- I am OK with this functionality at present. I don't think a priority.
