### ISSUE TITLE
Error message after deleting components

### ISSUE THREAD

**Issue by evomellor** [CenterForOpenScience/osf.io#2632]
Steps
-------
1. Create a new project
2. Create a component within project (I classified it as "Other" but I'm not sure if that is necessary to replicate the issue)
3. Delete that newly created XprojectX [Correction! Delete the newly created component]
4. Error message on parent project showing up under Components window: Error rendering template util/render_nodes.mako: KeyError('is_profile',)

Expected
------------
1. No error message

Actual
--------
1. This may be related to this issue: https://github.com/CenterForOpenScience/osf.io/issues/2628
2. You can see this issue on this project: https://osf.io/9c37b/

![screen shot 2015-05-05 at 10 00 38 am](https://cloud.githubusercontent.com/assets/11249723/7474264/383da57a-f30e-11e4-9dc7-4b1b7c54ef77.png)

**Comment by sloria** [comment]
Thanks for reporting. I'll look into this now.

**Comment by lbanner** [comment]
Can't seem to replicate this @evomellor -- Though I do see your error. @caileyfitz , when you get a chance, can you see what happens for you? Thanks.

**Comment by caileyfitz** [comment]
Steps for this issue are confusing, because step 3 says to 'delete the newly created project', but you can't delete the project without deleting the components first. Is this supposed to say 'delete the newly created component.' Or am I completing the wrong steps @evomellor? 

After deleting the *component*, here is what I see on the project overview page: 
![screen shot 2015-05-05 at 10 48 30 am](https://cloud.githubusercontent.com/assets/5975444/7475272/8f0a659a-f314-11e4-9e67-1afee0427c50.png)

**Comment by evomellor** [comment]
Yes, correct, "Delete the newly created component"

**Comment by sloria** [comment]
Sending a hotfix shortly.

**Comment by sloria** [comment]
@evomellor Should now be fixed

**Comment by GaryKriebel** [comment]
Looks good.

**Comment by evomellor** [comment]
Thank you!

**Comment by abought** [comment]
Looks good for me based on the steps listed above.
