### ISSUE TITLE
Confusing wording in OSF standard registration dialog

### ISSUE THREAD

**Issue by caileyfitz** [CenterForOpenScience/osf.io#2680]
Reported by @abought on the 0.35 Trello board:

## Summary

A question in the dialog for an *OSF-Standard Pre-Data Collection Registration* is confusingly worded.

When choosing this registration type, it asks:

`Is data collection for this project underway or complete?`

Choices are
- No
- Yes

## Proposed change
The meaning is unclear. If it is asking the user to choose one or the other, then the choices should be
- Underway
- Complete

If it is asking whether or not the project is past the planning stages, then further consultation may be needed on the best wording.

**Comment by HarryRybacki** [comment]
Are we assuming that data collection must have at least begun at this point? **Pre-Data Collection Registration** makes that seem counter intuitive. Perhaps three options would be better:

1. No data has been collected
2. Data collection is in currently in progress
3. Data collection is complete

**Comment by caileyfitz** [comment]
+1 to @HarryRybacki's suggestion

**Comment by abought** [comment]
Revisiting this a week later, @HarryRybacki 's suggestion seems like a good way to capture the situation.

Since this is the pre-collection registration, an alternative would be to reword in a way that emphasizes that "underway" and "complete" are a similar state of affairs (rather than being alternatives):

> Is data collection for this project underway / complete?
