### ISSUE TITLE
Inconsistency in project configuration: Name, Description, and Public/Private vs Category

### ISSUE THREAD

**Issue by sloria** [CenterForOpenScience/osf.io#2686]
## Steps

1. Edit your project name
2. Edit your project description
3. Edit your project category

## Expected

All should be configured the same way.

## Actual

Name and Description are inline editables. They cannot be changed on the project's Settings page. Category can only be changed on the Settings page. It is not inline-editable.

## Suggestion

Put all configuration on the Settings page.

**Comment by zkraime** [comment]
@GaryKriebel Can I take this too?

**Comment by lbanner** [comment]
You've got it @zkraime

**Comment by zkraime** [comment]
@sloria In the settings page, should we keep the title and description inline-editable or have an 'Edit' button? 
I had assumed the former but realized it might not be ideal

**Comment by sloria** [comment]
@zkraime For the initial iteration, just keep the title and description as is (inline-editable). I agree that it isn't ideal, but we can remove the inline-editables in a future iteration.

**Comment by zkraime** [comment]
OK thanks

**Comment by zkraime** [comment]
Here's what it looks like now: 
![screen shot 2015-06-05 at 12 02 18 pm](https://cloud.githubusercontent.com/assets/11323460/8010095/601dbd48-0b7b-11e5-9a78-43383567ffcd.png)
and:
![screen shot 2015-06-05 at 12 06 07 pm](https://cloud.githubusercontent.com/assets/11323460/8010101/67edd77e-0b7b-11e5-8b28-c8572cd3e825.png)

Should I go ahead and submit a PR now?

**Comment by sloria** [comment]
@zkraime Oh, I think I misunderstood your previous question. To clarify: the inputs on the settings page should *not* be editable inputs--they should be normal text inputs. I just meant that we can keep the editable inputs on the *Overview* page for now.

**Comment by zkraime** [comment]
@sloria Ah OK, understood. thanks

**Comment by zkraime** [comment]
@sloria I added edit links to the inline editables in the edit page. 
I wanted to make it so that you <b>can't</b>   also click on the title or description itself to edit it, but I'd have to duplicate code and use a different id so that it remains editable in the dashboard page. 
Is this OK? 
The only thing I was thinking is that the edit links should disappear while the input form is up and then reappear after canceling or finishing editing. 


![screen shot 2015-06-08 at 11 58 13 am](https://cloud.githubusercontent.com/assets/11323460/8039131/b7bddd74-0dd5-11e5-9552-c4d6fd71a77c.png)

![screen shot 2015-06-08 at 11 54 17 am](https://cloud.githubusercontent.com/assets/11323460/8039106/93b62166-0dd5-11e5-96ed-b6ee3c28beb8.png)

![screen shot 2015-06-08 at 11 54 34 am](https://cloud.githubusercontent.com/assets/11323460/8039111/96c2332c-0dd5-11e5-8135-c0445562e19c.png)

**Comment by sloria** [comment]
I don't think there's any reason to use inline-editable inputs on the settings page. Just use a normal text input for the title and a text area for the description.

**Comment by zkraime** [comment]
Okie dokes

**Comment by lyndsysimon** [comment]
Bug: special characters are not displayed properly in the title edit input:

![image](https://cloud.githubusercontent.com/assets/131414/8194138/976b94f8-1447-11e5-8445-493229af350c.png)

This project's title is "Alpha & Test"

**Comment by sloria** [comment]
The following also applies to the "Public / Private" setting; I would expect this could be done on the Settings page as well.

I'll update the issue title accordingly.
