### ISSUE TITLE
Wrong icons in file grid

### ISSUE THREAD

**Issue by brianjgeiger** [CenterForOpenScience/osf.io#2783]
Steps
-------
1. Go to the project organizer. Look at the icons
2. Go to the file grid. Look at the icons.

Expected
------------
Icons between each of those grids would be the same for the same items.

Actual
--------
Components and projects in the file grid have folder icons inside of their category icons.

**Comment by caneruguz** [comment]
@GaryKriebel this could be a good intern task as well.

**Comment by leb2dg** [comment]
Is this issue talking about the difference between the icon that appears next to project/component names in different views? If so, would you like the cubes/component icons (first image below) to be used instead of the folder icons (second image below)? @brianjgeiger 

![screen shot 2015-05-26 at 1 04 00 pm](https://cloud.githubusercontent.com/assets/7131985/7818161/f8de445c-03a7-11e5-9f51-4114be0d47c2.png)
![screen shot 2015-05-26 at 1 04 16 pm](https://cloud.githubusercontent.com/assets/7131985/7818162/fb75708c-03a7-11e5-88fe-02a74bb8b79e.png)

**Comment by brianjgeiger** [comment]
That is all correct, @leb2dg. Use the icons from the first image in all places.

**Comment by leb2dg** [comment]
Wonderful, I'll work on this.

**Comment by samanehsan** [comment]
Closed by #2871
