### ISSUE TITLE
Tooltip does not appear black consistently

### ISSUE THREAD

**Issue by NatashaRichter** [CenterForOpenScience/osf.io#2841]
# Steps
1. Go to a project on which you have admin or read/write access
2. In either the files tab or the files grid on the project overview page, click to select a file/folder
3. In the toolbar, look for the Rename option
4. Hover over the option to see if the black tooltip appears
5. Click on another file/folder
6. Check if tooltip is black.

# Expected
I expect to see the black tooltip upon hovering over the button.

# Actual
I see the yellow tooltip until I click onto another file/folder. 

#### When hovering over rename button: 
![screenshot 2015-05-26 16 44 48](https://cloud.githubusercontent.com/assets/7093086/7823352/e6c49110-03c8-11e5-845e-61439783302a.png)

#### After renaming and selecting another file to rename: 
![screenshot 2015-05-26 16 43 44](https://cloud.githubusercontent.com/assets/7093086/7823367/f7351c72-03c8-11e5-8325-ce237ce55137.png)

**Comment by lbanner** [comment]
@Caner -- insight on this one? Thanks.

**Comment by caneruguz** [comment]
We are moving away from the tooltips on the toolbar because they do not add value to the button, at least for the moment. This tooltip is removed in this issue:
https://github.com/CenterForOpenScience/osf.io/pull/2842

So we can close this when that is merged. 

For general information though, browsers have their own tooltips, if a tooltip is anything other than black that means the tooltip is not working and falling back to html defaults.

**Comment by haoyuchen1992** [comment]
@lbanner The tooltip has been removed on both staging and production. I think both this issue and #2844 could be closed now.

**Comment by lbanner** [comment]
Cool!
