### ISSUE TITLE
blue tab should also allow resizing of comment window

### ISSUE THREAD

**Issue by jlcohoon** [CenterForOpenScience/osf.io#287]
## Steps
1. Visit a project with commenting enabled
2. Click on the blue tab to open the comment pane
3. Click on the tab (i.e. not the blue border dividing the pane, but the tab with the chat icons) and try to drag to resize the pane.

## Current behavior
1. The tab itself cannot be used to resize the comment pane
2. The dividing blue border can be used to resize the pane

## Suggested Behavior
1. Clicking and dragging the blue tab should allow the user to resize the panel.

**Comment by samanehsan** [comment]
This can be closed after #2534 is merged since it changes the comment pane UI to remove the blue tab. Instead, the conversation bubble will appear in the project navigation bar:  
![screen shot 2015-08-13 at 11 38 47 am](https://cloud.githubusercontent.com/assets/6414394/9254145/edda1e00-41af-11e5-83be-d08e25f66575.png)

**Comment by samanehsan** [comment]
Closing this since the blue tab was removed with recent commenting UI changes and replaced with a conversation bubble icon on the nav bar.
