### ISSUE TITLE
Add instructions on how to upload files to files page

### ISSUE THREAD

**Issue by jlcohoon** [CenterForOpenScience/osf.io#2928]
This comes from the community repo: https://github.com/CenterForOpenScience/community/issues/191

<h4>Steps</h4>
1. Visit the files page of a project.

<h4>Outcome</h4>
1. Unless the user clicks on a storage add-on, there is no indication of how to upload a file anywhere on the page.
![screen shot 2015-06-02 at 10 55 30 am](https://cloud.githubusercontent.com/assets/4965832/7938999/9fe5925a-0916-11e5-9a4a-9b13d70826f2.png)

<h4>Expected outcome</h4>
1. It should be obvious to users how to upload a file: Adding a sentence of instruction ("Click on a storage folder or drag and drop to upload") could solve the problem.
![screen shot 2015-06-02 at 11 00 13 am](https://cloud.githubusercontent.com/assets/4965832/7939004/a410b3dc-0916-11e5-813d-c7f51a3b7ab8.png)

**Comment by chennan47** [comment]
@caneruguz This is the issue. Thought?

**Comment by caneruguz** [comment]
Thanks for the heads up. 

My suggestion is to include a more general text that says:
"Select a row for options or click [i] icon to learn more."

This text should only appear when no selection is made and the logic should go somewhere here: 
```js
        templates[toolbarModes.DEFAULT] =  m('.col-xs-12', m('.pull-right', [finalRowButtons, generalButtons]));
```
to add a text aspect like this
```js 
   var helpText = '';
   if(items.length === 0){
      helpText  = m('span', 'Select a row for options or click [i] icon to learn more.');
   }
        templates[toolbarModes.DEFAULT] =  m('.col-xs-12', m('.pull-right', [helptext, finalRowButtons, generalButtons]));
```

Or something along those lines. We can keep discussion on what the text should say.

**Comment by brianjgeiger** [comment]
An alternate is to have the files grid select the first storage location rather than the top level item by default. This would give an upload button if the user has write permissions whenever the user visits the page.

**Comment by bnosek** [comment]
My first thought was the the default selection as well, but I have a vague recollection that there was something wrong with that suggestion when I made it previously.  [It could be that the problem was I was the one making the suggestion...]

**Comment by JeffSpies** [comment]
Specifically mentioning drag and drop either above or below the region would probably be useful either way--I have a feeling that not all of our users are aware that that's possible.

**Comment by chennan47** [comment]
What about 
![screen shot 2015-06-02 at 12 07 23 pm](https://cloud.githubusercontent.com/assets/4974056/7940612/fd469f26-091f-11e5-976d-9de53f838b9c.png)

**Comment by bnosek** [comment]
should be in the gray bar to avoid taking up more space probably

**Comment by brianjgeiger** [comment]
No, that's far too heavy for something like this. If we do add some text, it should just be something small and probably under the grid, but we should remove it if we can get some site-wide contextual help in at some point (vaguely discussed from time to time, but no proposals yet).

**Comment by caneruguz** [comment]
The suggestion I made for where in the code this text should be places it in the grey bar. I think it should be at the top of the screen rather than bottom. 

Eventually (relatively soon maybe) we can start adding the general capacity for personalizing small UI components. At this point it can be a dismissable text.

**Comment by jlcohoon** [comment]
Dropbox defaults to the top level for what folder you upload to. They have an "add a document" button rather than an upload symbol, which might be more understandable to users. Since users can drag and drop files, defaulting probably doesn't pose an issue (not being able to move it might have been the problem before). Adding an icon instead of text could help us later if we add a file recovery page.

![screen shot 2015-06-04 at 11 25 25 am](https://cloud.githubusercontent.com/assets/4965832/7987718/228b235e-0aad-11e5-8ef5-f01e3b384975.png)

**Comment by caneruguz** [comment]
The top level is not quite so obvious in this case because the top level is the Project and then there are sub levels of add ons. Most likely the OSF Storage that belongs to the Project can be auto selected but that's not always the first thing visible depending on the add ons added. 

So I think there solution is to add a temporary text to the bar as Johanna initially suggested. It can say one of these two things:
1. "Select a row for options or click [i] icon to learn more." - a general placeholder for all possible actions that gives us a wider place to inform but itself doesn't give any information so it's successful to the extent that people follow it. 

2. "Drag and drop files to upload or select folders for more options." - specific to upload and more successful at conveying that message while also suggesting that more things are available.

**Comment by jlcohoon** [comment]
Semi related to https://github.com/CenterForOpenScience/osf.io/issues/3617

**Comment by GaryKriebel** [comment]
Closed via https://github.com/CenterForOpenScience/osf.io/pull/5636
