### ISSUE TITLE
Collapse multiple private components into one item in file tree

### ISSUE THREAD

**Issue by jlcohoon** [CenterForOpenScience/osf.io#2951]
From a community repo issue: https://github.com/CenterForOpenScience/community/issues/36

<h4>Current behavior:</h4>
Private components that are children of a project are listed in the file tree as separate items. When there is more than one, the list of private components grows. This can be distracting, and does not provide users with much information, considering how much space it can take up.

![screen shot 2015-06-03 at 1 43 50 pm](https://cloud.githubusercontent.com/assets/4965832/7967199/97e0cb0c-09f6-11e5-8367-d260cec3c80e.png)

<h4>Suggested behavior:</h4>
If a parent project has multiple children that are private, users that are not contributors on those private components should see them as being collapsed into one item that includes the number of private components. For example, if there were three private components, instead of listing "private component" three times, it would say "3 private components" in the file tree.

![screen shot 2015-06-03 at 1 46 22 pm](https://cloud.githubusercontent.com/assets/4965832/7967268/f25251e6-09f6-11e5-9382-b649054d9296.png)

**Comment by chrisseto** [comment]
+1 to this.
@lbanner could we have an intern start working on this soon?

**Comment by lbanner** [comment]
OK

**Comment by leb2dg** [comment]
I can work on this.

**Comment by lbanner** [comment]
Done - and thank you!

**Comment by leb2dg** [comment]
@jlcohoon / @chrisseto, @samanehsan suggested that this issue, and the way it should be handled, be put up for discussion. I have been assigned a project for the epic and so I may be pulled from this issue depending on how much time it will require.
### Details
Due to the way the data is processed and the rows are rendered, condensing the 'Private Component' rows into a single row is quite complicated. After trying some thing out and speaking with @caneruguz, it appears that the most efficient way to deal with this would be to manipulate the data before it is passed to treebeard. This could be done by adding/modifying a couple functions in *fangorn.js* (*onDataLoad* & *onLazyLoad*) that would loop through the data tree recursively. At each level of the data tree it would record the number of private components and remove all but one of those components. The number of private components would be appended to the name attribute of the single existing private node. Keeping a single private component would allow the row to be rendered properly. Warning: I have not tried to implement this solution yet so this description may be a little off

The simpler solution would be to not show the private components at all and handle them like the project organizer.

If you have other suggests I would love to hear them!

**Comment by lbanner** [comment]
Good review @leb2dg  ---  @jlcohoon @chrisseto Though not ideal, is the issue enough of a problem to either (a) Dig into and take time for a complex solution here - or - (b) Simply not display 'Private' components?

If we can live with the display as it is now, I'd suggest closing or deferring at present.

**Comment by jlcohoon** [comment]
I would opt to defer for now, but @bnosek, as the one who originally filed the issue, what do you think?

**Comment by brianjgeiger** [comment]
This is certainly something we could work into the V2 API. If you want the feature, we'll have to anyways, if you're going to want it, unless we make it all front end which, as we know, is complicated.

**Comment by lbanner** [comment]
Alright -- we'll file under "V2 API" for now, @brianjgeiger ... can you note on your roadmap? :smiling_imp: I'll tag with "hold" -- Thanks.

**Comment by caneruguz** [comment]
Actually this is a good point to discuss. Why are we showing private components to begin with? There is almost no functionality they have inside the files panel. Only showing an aggregate number is also as ineffective. I think they should simply be removed from the data source in rubeus.py or appropriate location on the back end; which I think is what the consensus is coming down to right @brianjgeiger ?

**Comment by brianjgeiger** [comment]
I believe currently the V2 API just filters out private components, so it would appear I agree with @caneruguz. Not showing someone something they don't have permissions to know about is more secure. Unless there's a really good reason to show it, I would support hiding those components entirely.

**Comment by jlcohoon** [comment]
Showing them was a conscious decision, though maybe we do want to
reconsider? The idea was to show people that there is some hidden content,
so they could at least be aware that there are additional parts to the
project. It's a very low level of transparency.

**Comment by caneruguz** [comment]
@jlcohoon That's a very reasonable thing to do, I think we all agree on that. Maybe file browser is not the place to show there are private components since neither they nor their files can be worked with in this environment. They should appear somewhere though and if I'm not mistaken they appear in the current Components widget right? But we may be revising that design as well. 

So as in all things, instead of deciding on the fate of this individual aspect we need to solve the bigger problem: What is the best way to tell people that there are subcomponents in a project that they can't access?

**Comment by brianjgeiger** [comment]
It makes sense from a certain perspective, but if someone wants to hide their private activity entirely, they could make a private project that holds everything that's not public, or if they want to keep from making it appear that there are many private components, they could make a private component and then move all the other private components into there. 

This changes significantly as we add more and more features to the API. Now that we have the arbitrary nesting, it's easy to do hiding. Once we have movable components inside a project, then it'll be easy for people to rearrange that way. Once we have the ability to rearrange between projects, then there's no way we could enforce even the most basic of transparency if it's important to whomever that it not be transparent.

So, all that being said, I just don't expect people care that much. Mostly it's a question of aesthetics. In the file list, it's very inconvenient to have unusable info, as Caner says. In the project summary page, it's a lot of real estate to say that there are private projects, because that widget takes up a lot of space per project. So I wonder, if we want to keep that information, if we might make it something a bit more interesting without interrupting the functional spaces.

For example, we could have a bit of metadata for a project that is an openness score. "This project is 74% open". That could be a very basic measure, such as number of components, or it could be something more involved, taking into account file sizes, where all the contributors are, or whatever. The more advanced, the more interesting, but the more basic, the less likely we are to make people upset by revealing something they didn't want revealed, or at least showing willingness to access that information even in an abstract, metadata gathering situation. So probably basic would be better.

Anyways, plenty of options for ways to display the information that will require their own proposals, but I think we can accomplish all of the goals without necessarily showing private components in places where people can't make use of that information.

**Comment by jlcohoon** [comment]
One further thing to consider is that there is currently a proposal being created (https://docs.google.com/a/cos.io/document/d/1lsaY7JNRmS7GfTtugtkDQegNOXINq-yi-ZUggez1gmU/edit?usp=sharing) to establish a system for Admins to be able to make the name of a private component visible and to allow other users to request access to that component. In that case, there is an actionable item for the user. Would we only want to show them those that they could request access to, or also list "private component" for the ones that the admin chooses not to share? And, in the file tree, is a private component with a visible name listed there? Or is it still excluded from the file tree?

**Comment by brianjgeiger** [comment]
We were talking about doing this API side, but after consideration, that seems wrong and we should keep it all in the UI.

**Comment by lbanner** [comment]
OK

**Comment by GaryKriebel** [comment]
Closed
