### ISSUE TITLE
Signing up for a gravatar.org is overly cumbersome

### ISSUE THREAD

**Issue by billyhunt** [CenterForOpenScience/osf.io#2979]
Steps
-------
A scientist friend using the OSF found it overly cumbersome to have to sign up for gravatar.org to have his photo on the site.

Expected
------------

The OSF has the ability to host their own images.

Actual
--------

A user has to go through many steps to show off how amazing they look.

**Comment by jinluyuan** [comment]
@billyhunt I also noticed that the only way to update my Gravatar is by clicking the default Gravatar on my public profile page. There is no actual place in Settings to change it. This might confuse some users, and some may not even know that they can change their avatar since it's not an option in Settings.

**Comment by billyhunt** [comment]
Very good idea.  I think it shows up if your email address is associated with your Gravatar image.  (like github, notice our snazzy images to the left ), but its not clear how to change it on our site, or that you can.

**Comment by nanchen47** [comment]
Will be considered in future profile page enhancement. Thanks.
