### ISSUE TITLE
[Production & Staging]: No limit on component title length

### ISSUE THREAD

**Issue by NatashaRichter** [CenterForOpenScience/osf.io#2993]
## Steps
1. Log in to osf.io
2. Add a component to a project for which you have admin or read-write permissions.
3. Create a really long title for the component (beyond 200 or so characters).
4. Click the "OK" button.

## Expected behavior

I expect that either the new component will be created with the title I chose or that a modal will appear saying that the component title is too long.

## Actual behavior

No modal appears and the user can just click the "OK" button over and over again with no change (the modal won't disappear unless the user clicks "Cancel"). This leaves the user unclear as to the reason for no action upon clicking the "OK" button.

## Screenshots
![screen shot 2015-06-05 at 5 06 05 pm](https://cloud.githubusercontent.com/assets/7093086/8015299/5b47fa7a-0ba5-11e5-937c-e40106178f5d.png)

**Comment by geeksnglitter** [comment]
@lbanner Can I fix this?

**Comment by geeksnglitter** [comment]
Okay very easy fix, but does raise the question of what the allowable length of titles should be. When creating a project or component - once the fix is in -  you will only be able to make a title of max length 200 when you first create it, but when you are editing titles you can still make them however long you wish. Is this the desired behavior?

![screen shot 2015-06-08 at 11 33 32 am](https://cloud.githubusercontent.com/assets/7839433/8038580/4d239254-0dd2-11e5-9cfc-f94f06df8fe7.png)

![screen shot 2015-06-08 at 11 33 18 am](https://cloud.githubusercontent.com/assets/7839433/8038577/47f63110-0dd2-11e5-9cf6-68dfdf8522f8.png)

**Comment by sloria** [comment]
@geeksnglitter  200 seems fine for now. In any case, validation should happen both on the frontend and the backend, so that we don't miss places where the title can be made longer than the max length, e.g. the settings page or the inline-editable input.

**Comment by lbanner** [comment]
Yours @geeksnglitter -- Thank you.
