### ISSUE TITLE
[Production & Staging] Button smashing the "watch" button causes watch count to show impossible numbers

### ISSUE THREAD

**Issue by jinluyuan** [CenterForOpenScience/osf.io#3201]
### Steps
1. Go to [osf.io](http://www.osf.io).
2. Go to any project.
3. On the project overview page, click the "watch" button (eye icon) once.
4. The number should either go from 1 to 0 or 0 to 1.
5. Now button smash the watch button.

### Expected behavior
I expected that the watch count would rapidly alternate between 0 and 1.

### Actual behavior
The watch count sometimes would go to -1, and sometimes it would rise over 1. Although it is not shown in the gif, I once got it go to up to 12 before it went back to 0. When the count displays -1, it causes the button to expand and move.

I discovered this kink when testing Haoyu's [tooltip fix](https://github.com/CenterForOpenScience/osf.io/pull/3174). The -1 problem happened within a few times of pressing the button, and it's very noticeable since the button jumps.

** Tested in Safari and Chrome

![watchbuttonproblem](https://cloud.githubusercontent.com/assets/8591162/8234465/1ec8a7e8-15aa-11e5-9127-63edb5848020.gif)

**Comment by lbanner** [comment]
"button smashing" :smile_cat: .... that a real term?

**Comment by brianjgeiger** [comment]
That is fairly industry standard. References to monkeys are also common.

**Comment by jinluyuan** [comment]
I originally had a more *professional* description, but really, button smashing is the most accurate term for it. Plus, it's fun to say button smashing.

**Comment by brianjgeiger** [comment]
So it definitely shouldn't go to -1, and that's an easy fix. Technically, it could go to 2, even though you're pretty sure it wouldn't, because other people could be clicking at the same time. It will fix itself before long; it won't stay on 2 or -1 even if you stopped clicking at the right time. Once the server returns, it will correct itself with the count based on everyone else's clicks as well.

That being said, the button should be disabled while it's waiting for a return from the server. Then everything would work properly in all cases.

**Comment by haoyuchen1992** [comment]
I replicated the error. It is quit possible that because the button has been clicked twice in one direction(Such as decrease). Then 1-2 = -1.  We may need to add additional logic to not allow it to happen.

I can work on this one.

**Comment by samanehsan** [comment]
Closed by #3221
