### ISSUE TITLE
[osf email] receiving two emails despite merged accounts

### ISSUE THREAD

**Issue by bnosek** [CenterForOpenScience/osf.io#3289]
I receive OSF announcement emails to:

nosek@virginia.edu
AND
ban2b@cms.mail.virginia.edu

At one point, these were separate accounts but they have been merged into a single account.  However, the email mechanism does not appear to recognize that.  

Simple solution is for me to unsubscribe one, but this will come up for users and become an annoyance.

**Comment by lbanner** [comment]
@bnosek I believe the functionality is such that, even though both emails are tied to a single account, they both remain active and therefore both possible to receive our OSF / system emails.

**Comment by GaryKriebel** [comment]
@samanehsan would this be easy to correct now that email merging as been in effect?

**Comment by bnosek** [comment]
right - a bug not a feature.  User would not expect to receive multiple
emails when they are tied to a single account.

**Comment by GaryKriebel** [comment]
I think it is a reasonable expectation that the primary email is the email that is subscribed.  After merging, you do not have access to the "Configure Email Preferences" for the former stand alone account.

![screen shot 2015-06-24 at 8 55 12 am](https://cloud.githubusercontent.com/assets/9437946/8330354/cf91f69e-1a4e-11e5-9474-7b3a9a134312.png)

There may be some discussion required for the cases where nosek@virginia was unsubscribed, ban2b@ was subscribed, and the latter is merged into the former.... inherit the primary of unsubscribed or subscribed because one of the two was subscribed.

**Comment by samanehsan** [comment]
@GaryKriebel, I can look into this now

**Comment by lbanner** [comment]
Thanks @samanehsan

**Comment by sloria** [comment]
This should now be fixed.
