### ISSUE TITLE
Improve functionality and appearance of FAQ page

### ISSUE THREAD

**Issue by jinluyuan** [CenterForOpenScience/osf.io#3350]
The [OSF FAQ](https://osf.io/faq/) page lacks any navigation or grouping of questions, which causes the user to take longer to find the question that applies to his situation. The page is also very static and plain.

Examples of a more modern, user-friendly style of FAQ page are [Github](https://help.github.com) and [Figshare](https://figshare.zendesk.com/hc/en-us).

**Comment by lbanner** [comment]
As we grow in user-base, and improve OSF functionality, it will become more critical that this page be easy to navigate and understandable for our users.

**Comment by mfraezz** [comment]
It looks like it’s not only poorly organized but also incorrect in a number of places due to recent site updates (e.g. whether or not files can be renamed). It might be good to have QA look over it for inaccuracies, as they know site functionality best, and also to have someone who communicates with users frequently to check if there are any common questions not on the FAQ.

**Comment by jinluyuan** [comment]
@lbanner If you want, I can make an overview of necessary content additions and changes, and we can build from that. At the very least, we should fix the incorrect information that @mfraezz pointed out as soon as possible. This might apply to Getting Started as well.

**Comment by lbanner** [comment]
Agreed - Yes, thank you @jinluyuan (OSF Editor)
