### ISSUE TITLE
Links to external sites should open in new page

### ISSUE THREAD

**Issue by jinluyuan** [CenterForOpenScience/osf.io#3419]
Many external links on osf.io open up in the same page when they should open a new tab. The hyperlinks need the "target=_blank" attribute.

Examples:
1. Clicking External Link on a project
2. Clicking "Create Access Token" when configuring add-ons
3. Clicking the social links in the footer
4. Clicking the Gravatar link in the Change Avatar modal

**Comment by sloria** [comment]
I'm not sure if we should do this for *all* external links. @caneruguz This might be a good thing to document in the style guide once we nail down a best practice.

**Comment by caneruguz** [comment]
I share this perspective : http://www.smashingmagazine.com/2008/07/should-links-open-in-new-windows/

Opening a link in a new window should be reserved for situations when it makes sense that the current page should continue to be available for a good reason (other than keeping people in our site). Otherwise users will have proliferation of tabs or would have to come back to close the OSF tab. Some people are also not very good with tab management and may not find where the new window open. In some devices like mobile devices, tabs and new windows are not immediately visible and users may think the link did not work. 

So there are several good reasons to not open external links on the page.

**Comment by caneruguz** [comment]
@GaryKriebel @sloria  should this issue be closed?

**Comment by nanchen47** [comment]
Based on the discussion above, close this one.
