### ISSUE TITLE
in search results, registrations of the same project cannot be distinguished from one another

### ISSUE THREAD

**Issue by jlcohoon** [CenterForOpenScience/osf.io#3615]
from the community repo: https://github.com/CenterForOpenScience/community/issues/276

## Steps
1. Search the OSF for a project that has been registered multiple times (try searching "local versus global")

## Outcome
1. Registrations of the same project are listed as separate results
2. The registrations are indistinguishable from one another
3. They do not necessarily appear next to each other or in recent to oldest order.
![screen shot 2015-07-15 at 10 54 27 am](https://cloud.githubusercontent.com/assets/4965832/8701462/e72f9b52-2adf-11e5-9cf7-bc7e604af613.png)

## Suggested Behavior
1. Registrations should be distinguishable from one another.
2. They do not have to be listed as separate results. One suggestion is to collapse registrations of the same project that are returned in search results into one result, with the option to expand that result. On expansion, the different registrations and their dates could be shown and linked to. If this model is followed, I would suggest making the link visible when unexpanded (the title of the registration int he image below) link to the project's registrations page, so that the user is brought to a place where they can see each registration listed.

![screen shot 2015-07-15 at 11 06 59 am](https://cloud.githubusercontent.com/assets/4965832/8701744/a40c7a3c-2ae1-11e5-9121-604daf3cb0e3.png)

Of course, this could almost certainly be improved visually, but the basic idea is there.

**Comment by Johnetordoff** [comment]
@lbanner I like the suggested idea can I start working on it?

**Comment by lbanner** [comment]
I'll assign you @Johnetordoff -- But want @jlcohoon thoughts here also on this solution. @jlcohoon? Thanks.

**Comment by brianjgeiger** [comment]
Just so you know, I'm expecting this might be a little complicated. Right now, we are just asking Elastic for results and displaying them. Elastic doesn't really understand about registrations being a part of another project, in the way that it doesn't understand that components belong to projects as such. Trying to find a way to handle this after Elastic is done with it won't work well, because Elastic handles sorting and pagination. This implies that we need to make changes to the Elastic search to make it work better.  Because we are using the Lucene search syntax, we may be somewhat limited in our methods of interaction. I don't know if we can combine aggregations with Lucene, for example, which would almost certainly be necessary. 

The short of it is that we will probably want to have a proposal done for the change, and probably someone will need to have a conversation with @fabianvf about what's likely to be feasible and what isn't.

**Comment by jlcohoon** [comment]
I suggested it, so I'm a pretty big fan of the plan. I'm happy to write/assign someone to write a proposal for it if need be.

**Comment by brianjgeiger** [comment]
If we're doing something fancy, it might be cool to aggregate all of the components that match a project as well. So, for example, if you searched for `Reproducibility Psychology`, then RPP would show up at the in the list, and all of the components would be accessible from the search page, rather than necessarily being each individually listed as a component. This should, in turn, cause RPP to be waaaay high up in the search results (which is a separate issue).

This might be different enough not to do all in one go. It might make sense to try it out with registrations and do components as a separate thing or not at all, but having it in the back of the head during design is not a bad thing.

**Comment by lbanner** [comment]
Might a less fancy solution be simply changing the way we name Registrations? Say, for instance, adding a date in the name/title?

**Comment by jlcohoon** [comment]
I'd think that that's a good solution for now. More fanciful work could be saved for the future. @lbanner how might we preserve the other suggestions for future work? I do think @brianjgeiger's suggestion would be a good enhancement.

**Comment by Johnetordoff** [comment]
How do you think the date should be formatted, to the minute or just to the day? I don't think it's out of the question you'd have two registration on the same day, but having a lot of extra digits in such small font makes it difficult to read. Is there any style guide rules about dates?

**Comment by jlcohoon** [comment]
Not sure, probably not though.  You can check here: https://centerforopenscience.github.io/osf-style/
I'd say that for registrations, down to the minute is most helpful.

**Comment by GaryKriebel** [comment]
I would agree with @jlcohoon that to the minute would be ideal ... there may be a reason that you registered twice in a day (forgot to add a component prior to registration) and would want to make sure you know which is the most recent

**Comment by lbanner** [comment]
+1

**Comment by Johnetordoff** [comment]
@caneruguz and I are working on amending the Style Guide to include rules on displaying date/time. Any input is appreciated.

**Comment by caneruguz** [comment]
@sloria any input on this?

**Comment by sloria** [comment]
re: Displaying date times--we currently display datetimes in localized iso8601 format, with a tooltip for UTC time. I think we go with that for now.

**Comment by fabianvf** [comment]
I think ISO 8601 is ideal for storage of dates, as it is easily machine readable, but I'm not sure it is the most human friendly representation. I think something like ```February 2nd, 2015 at 8:00PM``` is much friendlier to display.

**Comment by caneruguz** [comment]
:+1: for Fabian, 

There was an extensive discussion on this earlier: https://github.com/CenterForOpenScience/osf.io/issues/668

**Comment by Johnetordoff** [comment]
I"m moving ahead with the dating individual entries option, if nobody has any more input. Also here's my purposed style guide guidelines for dates. It just tries to keep everything consistent with the log's datetime display:
<h3 id="datetime">Using Datestime</h3>
<p>All dates are to be displayed in <a href="https://en.wikipedia.org/wiki/Coordinated_Universal_Time">UTC</a> and should be precise down to minute. Ideally dates should be bolded and appear with a explainatory tooltip. You may also want to include information about the timezone if many datetimes are listed.</p><p>Example</p><b><span data-toggle="tooltip" data-placement="right" title="2015-01-23 17:42 UTC">2015-01-23 1:42 PM</span></b>

**Comment by lbanner** [comment]
:+1: as long as @jlcohoon is on board!

**Comment by caneruguz** [comment]
I think there is no obstacle to go ahead with the date time to fix this specific issue. 

However in terms of adding the concept to the style guide I would pause there. Since the goal of the guide is to have a conversation about the standards we have we should discuss it there: 

https://github.com/CenterForOpenScience/osf-style/issues/65

After that issue is resolved we can go ahead and quote it for future date related style questions.

**Comment by lbanner** [comment]
I support that thought/plan, but who currently has eyes on the StyleGuide? --- need a way to raise visibility on that when discussion/decision needed. In this case, I will raise it. Thanks.

**Comment by lbanner** [comment]
@Johnetordoff Based on discussion and direction here: https://github.com/CenterForOpenScience/osf-style/issues/65 We are good to go on your approach. Thanks.

**Comment by sloria** [comment]
> I think ISO 8601 is ideal for storage of date(time)s, as it is easily machine readable, but I'm not sure it is the most human friendly representation. I think something like February 2nd, 2015 at 8:00PM is much friendlier to display.

I disagree. ISO 8601 is an effective way to display **dates** in a [human-friendly](https://xkcd.com/1179/), non-locale-specific way (keep in mind that we don't localize dates at the moment). **Datetimes** should be displayed as they are on the site now--`YYYY-MM-DD hh:mm A`, using the [FormattableDate](https://github.com/CenterForOpenScience/osf.io/blob/4821e40194bee984849d76a47e9affc8f03caf3d/website/static/js/osfHelpers.js#L508-519) helper.

**Comment by caneruguz** [comment]
@sloria XKCD does not count as human friendly, sneaky move there though, adding it as a supporting link! 

But seriously I don't think you can find good support for ISO 8601 being user friendly method to display dates; which is okay. We have very good reasons to use that style. We support a community of science from all over the world; standardization, ability to render dates in many different computing systems and fairness is very important.

**Comment by sloria** [comment]
@caneruguz makes a fair point, though I think this discussion is outside the scope of this issue. As you pointed out, we had already come to a decision after discussion in https://github.com/CenterForOpenScience/osf.io/issues/668 . A suggest further discussion on displaying dates happen in the osf-style tracker.
