### ISSUE TITLE
Help and Explore buttons don't have expanding icons in narrow view

### ISSUE THREAD

**Issue by wisherp** [CenterForOpenScience/osf.io#3627]
Reported on 0.42 trello board by @caneruguz 
Link to the card: https://trello.com/c/LIqHglBO/64-help-and-explore-buttons-don-t-have-expanding-icons-in-narrow-view
# Steps
1. Log in to osf.io
2. Make the window narrow until you do not see Help and Explore on the dashboard 
3. Click on the menu icon (three lines) next to search
4. Look at Help and Explore

# Expected
A downward caret next to both Help and Explore indicating that they each have more content

# Actual
No downward caret. The contents show up only when the user clicks on Help/ Explore

 
![image](https://cloud.githubusercontent.com/assets/10926926/8707287/f24ccdfc-2b02-11e5-88b5-47196dcf5fce.png)

**Comment by haoyuchen1992** [comment]
Comparing with [Original code](https://github.com/CenterForOpenScience/osf.io/blob/41f177cb99f8c6bb64cb374e2ce726f40d84ea63/website/templates/nav.mako#L29) and [Current Code](https://github.com/CenterForOpenScience/osf.io/blob/develop/website/templates/nav.mako#L30), it looks like we add `hidden-xs` class to the expanding icons.  

@caneruguz  Is it intentional to do that ? I prefer to retain the expand icons.

**Comment by caneruguz** [comment]
No it's not intentional, we should fix it. Do you want to take this one?

**Comment by lbanner** [comment]
Tagging @haoyuchen1992 : )

**Comment by haoyuchen1992** [comment]
@caneruguz @lbanner  OK, Got it!

**Comment by haoyuchen1992** [comment]
This has been fixed and could be closed now! Thanks!

**Comment by lbanner** [comment]
Got it. Thanks.
