### ISSUE TITLE
clicking out of project navigation dropdown should close navigation

### ISSUE THREAD

**Issue by jlcohoon** [CenterForOpenScience/osf.io#3677]
## Steps
1. Visit an OSF project
2. Reduce the width of your window until the navigation collapses
3. Open the project navigation dropdown
4. Click elsewhere on the screen (not on the dropdown items,  e.g. bottom half of this image)

![screen shot 2015-07-17 at 1 54 14 pm](https://cloud.githubusercontent.com/assets/4965832/8754668/3ea3235e-2c93-11e5-8c26-5e739ca23c20.png)

## Behavior
1. Nothing happens

## Expected Behavior
1. Clicking elsewhere on the screen should close the dropdown

**Comment by caneruguz** [comment]
@jlcohoon I don't think this is the expected behavior in general. In a lot of mobile devices the space remaining of the page is very small anyway so it's not a very beneficial feature. 

**Example of iPhone 5 for instance:** 
![screen shot 2015-07-21 at 2 03 22 pm](https://cloud.githubusercontent.com/assets/1314003/8808579/6cb43e2e-2fb1-11e5-8ecb-5d7142afdcd3.png)

Also Bootstrap is not doing it in their website.

**Comment by haoyuchen1992** [comment]
Originally, I also thought the dropdown menu should be closed after user clicked on other area. After I test some companies' website, I found none of them did that. It makes sense for me now. In mobile setting, it is easy to click something by mistake.  It may be annoying for user when they click other places and the dropdown disappears unexpectedly.

**Comment by jlcohoon** [comment]
If click away isn't the solution, then the menu should push the content down, not cover it up. Note that in that image the project title is blocked.

**Comment by brianjgeiger** [comment]
I tend to agree; an element as important as the menu should not cover in XS, it should displace.

**Comment by caneruguz** [comment]
That's a good point, in that case though the navigation can't be fixed so that it can scroll with the page which is not a trivial change but that's what bootstrap is doing so there is good example there.

**Comment by caneruguz** [comment]
@jlcohoon @lbanner 
So the finalized task I think is this: 
- In small windows (XS view) make the project menu expand and push the content lower instead of being fixed. (Which means users will need to scroll to the top) 

This is what it would look like 
![nav_push](https://cloud.githubusercontent.com/assets/1314003/9256649/bc9bee68-41be-11e5-8b95-f3e66b8a0011.gif)

@erinmayhood is this something we should do?  Making this change would be minor and it would not change user expectation.  

On a side note: You'll see that the comment icon is causing issues there but that placement will be fixed. I'm inclided to also change comment pane to open to full width at that point for small devices.

**Comment by lbanner** [comment]
That's good!

**Comment by jlcohoon** [comment]
I think this is wonderful!
