### ISSUE TITLE
Issues with registering a project with a component - (files, read/non-contributor)

### ISSUE THREAD

**Issue by GaryKriebel** [CenterForOpenScience/osf.io#3722]
## Summary
This issue deals with a registering a project where the admin has either read-only permissions or is not a contributor to a component that has at least one file.  The project never fully registers as the component gets stuck in the archiving state. 

## Steps to reproduce:
1. Create a project
2. Add a file to your project (1 file in OSF Storage is fine)
3. Add a contributor to your project
4. Add a component to your project
5. Add a file to the component of your project (1 file in OSF Storage is fine)
6. Add your contributor to your new component (make them admin)
7. Register your project 4 times with your permissions changed on the component as such:

   7a. Register the project while you are an **"Admin"** to the component

   7b. Change your permissions to **"Read+Write"** on the component and then register the project 

   7c. Have your contributor change your permissions to **"Read"** on the component and then your register the project 

   7d. Remove yourself from the component and then register the project 

## Expected
I would expect to be able to successfully register the project in each of the cases above (7a - 7d).

## Actual
7a. **CAN** successfully register the project
7b. **CAN** successfully register the project
7c. **CAN NOT** successfully register the project (component is stuck on archiving - the registration looks complete on the registration page but upon clicking the registration you will see the "Archiving" tag on the component and it will never complete)
7d. **CAN NOT** successfully register the project (component is stuck on archiving - the registration looks complete on the registration page but upon clicking the registration you will see the "Archiving" tag on the component and it will never complete)
![screen shot 2015-07-21 at 12 11 07 pm](https://cloud.githubusercontent.com/assets/9437946/8805878/a2b2ff02-2fa1-11e5-887b-313b721b5a61.png)

**Comment by GaryKriebel** [comment]
@HarryRybacki @chrisseto @sloria 
So this does look to be a permissions issue since the admin has no issues as being admin or read/write on the component but does have issues when read/non-contributor on the component.  It also happens only when a file is present in the component.  A fileless component works fine.

The admin SHOULD be able to register the project in all instances as of release 0.26 (see https://github.com/CenterForOpenScience/osf.io/pull/1725 and https://trello.com/c/kkx1lFlP/8-registration-completeness ).... however, it may not have been tested with files at the time.

Can we first determine if it is an archiver or waterbutler issue and then go from there?

**Comment by HarryRybacki** [comment]
@GaryKriebel I'm not sure we have a good way to tell what service is failing -- Did @samchrisinger  or anyone else ever build the Archiver kill switch we said would be a good idea?. @sloria @chrisseto if you have any ideas let me know. For now I'll just setup the project as noted and try to follow the code down as far as I can.

**Comment by GaryKriebel** [comment]
I do not believe there has been any "kill switch" added.  For this particular issue, I would start with getting it to work with OSF storage as that is the current issue in the field.  Solving for that may take care of the permissions for others as well.

**Comment by HarryRybacki** [comment]
@GaryKriebel @sloria @chrisseto 
The source of the problem is [here](https://github.com/CenterForOpenScience/osf.io/blob/develop/website/archiver/tasks.py#L182). 

Archiver is creating the API token to be handed to WB for the user that initiated the registration. However, that user may or may not have [admin/read+write] privileges for the parent project's components. As a result, WB will kick back the `copyto` request of the new *registered component* which they do not have write access to.

Currently, I'm working on a solution that will ensure that the task itself will always create a API token for a user with admin rights of the registered component (which may or may not be the user that initiated the registration). 

**If** for whatever reason a component has no admins, or users with read/write access it will be unregisterable with the way our system currently works.
