### ISSUE TITLE
Wiki menu - Collapsed menu is taller than expanded menu

### ISSUE THREAD

**Issue by jinluyuan** [CenterForOpenScience/osf.io#3789]
![wiki collapse](https://cloud.githubusercontent.com/assets/8591162/8858281/932ef1fe-3144-11e5-9c67-a2f2e21053f2.gif)

This is distracting since it can stretch the height of the page/move the footer down. The very tall collapsed menu also just looks strange with all the blank gray space. It would be best if it were the same height as the standard Treebeard menu.

**Comment by lbanner** [comment]
@caseyrollins Is this in your dev realm on this piece-o-functionality?

**Comment by caseyrollins** [comment]
@lbanner, I believe the collapsed menu height was set before I changed the menu. I think the intention of the height setting was that it would line up with the height of the other wiki panels, as shown here: 
![screen shot 2015-07-23 at 3 39 04 pm](https://cloud.githubusercontent.com/assets/7913604/8860327/0a8bd36e-3151-11e5-9be4-fad73ce50a32.png)


However, this was/is inconsistent with the collapsible menu on the files page, which looks like this:
![screen shot 2015-07-23 at 3 39 24 pm](https://cloud.githubusercontent.com/assets/7913604/8860369/60356be0-3151-11e5-9575-c00def871141.png)


Personally, I think the collapsed menu on the files page is too short, but perhaps this should be discussed more so that if this is changed, the two implementations will match.

**Comment by lbanner** [comment]
OK thanks -- Ping @caneruguz on thoughts.

**Comment by caneruguz** [comment]
For the wiki:  This was a bug when we were first developing it and we resolved it before moving to production on the original wiki panel changes. So something has happened to break it in the meantime. 

The file detail page: I was not involed with that but i think in that case there isn't any code that is supposed to make it fit the height of the other segments. 

Both these can be fixed by making sure at collapse the heights of these containers align with the others. The thing that complicates this is that in wiki when only one item is visible height is not forces and in files the rendered file is not height limited. The best thing to do would be for both of these items to maintain the original (uncollaped) height of their respective containers.

**Comment by jinluyuan** [comment]
I noticed that this is an even bigger issue when visiting a wiki to which the user does not have write access. The collapsed wiki menu is empty and looks like a bug.

![screen shot 2015-08-13 at 4 48 03 pm](https://cloud.githubusercontent.com/assets/8591162/9261343/3fadd124-41db-11e5-8d80-8fdbc1e38a62.png)

It would be best if the collapsed wiki menu didn't have all the extra gray space at all. For write users, it would stop at the end of the New and Delete icons. For read-only users, it would appear the same as the collapsed file detail's menu (a simply expand button).

**Comment by erinmayhood** [comment]
Fixed
