### ISSUE TITLE
Profile Information - GitHub input form should not have rounded corners

### ISSUE THREAD

**Issue by jinluyuan** [CenterForOpenScience/osf.io#3808]
### Steps
1. Go to osf.io
2. Go to your user settings page
3. Look at the input form for GitHub

### Expected
I expected that the gray background helper info would connect seamlessly with the input form.

![screen shot 2015-07-24 at 1 51 39 pm](https://cloud.githubusercontent.com/assets/8591162/8881208/195e730e-320c-11e5-9685-dfdbaa7ba94c.png)

### Actual
The GitHub input form has rounded corners where it meets with the gray background helper info.

![screen shot 2015-07-24 at 1 51 18 pm](https://cloud.githubusercontent.com/assets/8591162/8881207/195e6a58-320c-11e5-8c21-c8d83d0afde4.png)

**Comment by haoyuchen1992** [comment]
The reason behind this is because we use a btn-group inside a btn-group, which results in the border issues. I change it into use one btn-group.

Here is the result:
![screenshot 2015-07-24 17 08 37](https://cloud.githubusercontent.com/assets/5420789/8884711/dff61462-3226-11e5-985c-02839e23d9ad.png)

If this is OK for every one, I could send a PR for that!
