### ISSUE TITLE
Navigation box in user and project settings become obscured upon zooming out in Safari

### ISSUE THREAD

**Issue by caileyfitz** [CenterForOpenScience/osf.io#3811]
# Steps
1. Log into osf on **Safari**
2. Go to user settings page
3. If on a Mac, hold Command and press the minus sign to zoom out and make more of the page visible
4. Start to scroll down the page and pay attention to the navigation box on the left side of the page

# Expected
I expect that the navigation box would remain on the left side of the page and would scroll appropriately according to content.

# Actual
The navigation box becomes obscured by the different section widgets of the page upon scrolling:

![user settings scroll](https://cloud.githubusercontent.com/assets/5975444/8883752/424e6310-321f-11e5-8287-e72d43057c66.png)

### Going to project settings and doing the same thing yields similar results:
![project settings scroll](https://cloud.githubusercontent.com/assets/5975444/8883778/79fa63e0-321f-11e5-9c37-941f985c1ed9.png)

**Comment by haoyuchen1992** [comment]
@lbanner I can work on this. Thanks!

**Comment by haoyuchen1992** [comment]
### Analysis
This issue is denoted in bootstrap [official docs](http://getbootstrap.com/javascript/#affix-usage).
> Note: Do not use the affix plugin on an element contained in a relatively positioned element, such as a pulled or pushed column, due to a Safari rendering bug.

Here is the github issues on bootstrap repository -- https://github.com/twbs/bootstrap/issues/12126

### Possible Solution
Currently, I don't find a stable solution. Since it only happens in Safari,  it may be better to add specific javascript code suggested in github discussion.  What do you think ? @caneruguz
