### ISSUE TITLE
Project Settings: 'Configure Notifications' link in the side navbar is broken

### ISSUE THREAD

**Issue by wisherp** [CenterForOpenScience/osf.io#3872]
# Steps
1. Log in to osf.io
2. Go to a project for which you have admin access
3. Click on the Settings tab
4. On the left nav-bar, click on 'Configure Notifications'

# Expected
The link would be highlighted and the page would scroll just above the header

# Actual
'Configure commenting' link is highlighted when 'Configure Notifications' is clicked and the page scrolls to the middle

![cannot click on configure notifications](https://cloud.githubusercontent.com/assets/10926926/8967143/3babbe76-3603-11e5-92d0-60775561085e.png)

**Comment by Johnetordoff** [comment]
@wisherp I actually caused this as part of this PR, #3642.
It's not really a bug it just defaults to the last box on the bottom of the page, it doesn't happen if the font is big enough.

**Comment by chennan47** [comment]
@Johnetordoff can you fix that problem and also there is some other problem about that panel on my mac. So when I click on the "Configure Project",
It's like 
![screen shot 2015-07-29 at 3 22 23 pm](https://cloud.githubusercontent.com/assets/4974056/8967563/a4cfe862-3605-11e5-9ccf-6ef8f8a2a298.png)
When I click on anything else on that table. It's like:
![screen shot 2015-07-29 at 3 23 17 pm](https://cloud.githubusercontent.com/assets/4974056/8967579/c2483df4-3605-11e5-999e-e673f9742bd4.png)
![screen shot 2015-07-29 at 3 23 45 pm](https://cloud.githubusercontent.com/assets/4974056/8967591/d40f186e-3605-11e5-9dfb-db27d8dcf087.png)

Watch the width of the panel table. This problem only happens to me when I have the "Configure Add-on" options.

**Comment by Johnetordoff** [comment]
@nanchen47 I'll take a look at the width issue.

**Comment by jinluyuan** [comment]
[Relevant Trello card](https://trello.com/c/dXX6OioD/51-match-style-of-all-side-nav-bars-getting-started-faq-public-activity-user-settings-project-settings)

> July 20
The second issue is not a bug with the implementation. It's just that these two sections are too close to the bottom so there isn't a proper way to put them up. When the content is long, like there are a lot of notification boxes then it will work as expected. There is nothing wrong with that implementation from a technical point of view.

> July 17
Project Settings - The Configure Notifications link doesn't seem to work at all. I can hover over it, but when I click on it, I get taken to Configure Commenting. Thus, Configure Commenting is shown as the "active section" instead of Configure Notifications.

**Comment by NatashaRichter** [comment]
@wisherp @sloria Can we reopen this issue? It's happening again on Production for Chrome and Firefox. Or I can make a new issue for it? I think @haoyuchen1992 was looking into it on the 0.45 board. See trello card here: https://trello.com/c/GL7NB99k/31-configure-notifications-and-configure-commenting-are-not-highlighted-upon-click

**Comment by nanchen47** [comment]
@haoyuchen1992 any update on this one?

**Comment by haoyuchen1992** [comment]
@chennan47  I had discussed with @sloria. And We decided to defer this issue. And the details is commented in the trello [card mentioned aboved](https://trello.com/c/GL7NB99k/31-configure-notifications-and-configure-commenting-are-not-highlighted-upon-click).

> Because the highlight of affix is controlled by the scroll position. When bottom panel is small, it can be never scrolled to the top. Therefore, it will never be highlighted. The is because we add data-bottom-offset for affix. Afterwards, it can not scroll down to the end and then will not overlap with the footer.

Basically, the cause is the side effect of adding affix-bottom. Here is the code  link--https://github.com/CenterForOpenScience/osf.io/commit/3cd5560659dafa84f239d5947742cf325fd0cfc5#diff-5a667408094f4a53c2cf6b0848aa2e3bR25
