### ISSUE TITLE
[Safari] Project settings side navbar needs more space on small screen

### ISSUE THREAD

**Issue by NatashaRichter** [CenterForOpenScience/osf.io#3908]
## Description

On a small screen on Safari, there is no space between the side navbar and the rest of the page content on the project settings page.

![no_space_side_navbar](https://cloud.githubusercontent.com/assets/7093086/9038931/07ab1754-39c6-11e5-97de-a57f1c04dec2.png)

On Chrome and Firefox, there is space between the side navbar and the rest of the page content.

![adequate_space_side_navbar](https://cloud.githubusercontent.com/assets/7093086/9038872/b0caa7f6-39c5-11e5-8805-2a9ad5535183.png)

**Comment by haoyuchen1992** [comment]
@lbanner This issue may be similar as https://github.com/CenterForOpenScience/osf.io/issues/3811 . I can also work on it! Thanks!

**Comment by haoyuchen1992** [comment]
This issue only happens when user internationally reduce the size of screen.  When resizing the browser windows, the correct change will not reflect instantly and therefore we see the margin is missing. If refreshing the page, the margin is there.

Therefore, I am confusing whether this should be a bug. It looks like related to the inner rendering process of browser. What do you think of it? @caneruguz @sloria

**Comment by caneruguz** [comment]
@haoyuchen1992 There should be some information on this online, users of bootstrap might have reported this happening in Safari. I would do some research on this. If this is a common browser bug with bootstrap there will be other users talking about it and it could provide insight into what's going on. Safari is an important browser; we should try to fix this if we can so it's worth looking further into it.

**Comment by haoyuchen1992** [comment]
@caneruguz Forget to mention that this bug happens in all the four major browsers.  I will look  into it more.

**Comment by haoyuchen1992** [comment]
After discussing with Caner, we found the reason behind this was about the debounce time for updating affix.
