### ISSUE TITLE
[Staging and Production] Zotero does not give error message when credentials are revoked

### ISSUE THREAD

**Issue by WillBanner** [CenterForOpenScience/osf.io#3923]
This has the exact same behavior as issue #3748 

# Steps

1. Go to a project on which you have admin access
2. Go to project settings and enable and configure Zotero
3. Confirm that Zotero is configured and files are linked
4. Log on to your Zotero account.
5. Go to settings (in the upper right) > feeds/API
6. Click to edit, then revoke, the key for your most recently configured Zotero add-on.
7. Go to the project settings and refresh the page/ click to change the folder for Zotero.

# Expected
A message would appear stating that the OSF "Could not retrieve Zotero settings at this time. The credentials associated with this Zotero account may no longer be valid. Try disconnecting and reconnecting the Zotero account on your account settings page."

# Actual
There is no message to let me know that something is wrong and when I click to change the folder, the folder browser gets stuck loading.

![image](https://cloud.githubusercontent.com/assets/12799635/9047061/322090ae-39fd-11e5-89c8-c86a900ff1ec.png)

**Comment by mfraezz** [comment]
This happens because of an underlying problem with the oauth system for citations (and Dataverse), specifically with the way we're [verifying auth](https://github.com/CenterForOpenScience/osf.io/blob/develop/website/addons/base/__init__.py#L565). We're checking only to see that one or more external accounts are associated with the osf user's account, not if that association is still valid on both the osf side and the addon side. This is also an issue for [Dataverse](http://dataverse.harvard.edu) (`name -> account info -> edit account -> api token -> regenerate` to test for this), and almost certainly would be for Mendeley if I could figure out how to revoke that key.

It's probably possible to make a trivial api call in the method I link above to check for `HTTP4XX` errors, if so that would be a solution. @lyndsysimon might know of a better way, though.
