### ISSUE TITLE
API docs incorrectly display "links" type as "string"

### ISSUE THREAD

**Issue by sloria** [CenterForOpenScience/osf.io#4007]
It should say "object".

![swagger_ui](https://cloud.githubusercontent.com/assets/2379650/9207136/a02d38bc-4039-11e5-8f9b-0492d3abd502.png)

**Comment by brianjgeiger** [comment]
@pattisdr Does this still happen in your JSON API Branch?

**Comment by pattisdr** [comment]
Yes, links is still using "LinksField" and I haven't made any changes there.

**Comment by brianjgeiger** [comment]
Okay. Poking around just a bit, I expect this is a django-rest-swagger thing rather than a DRF thing, but I'm not positive.

**Comment by brianjgeiger** [comment]
On the other hand, when you get the options for the nodes/{nid} endpoint, it returns a type for each field. So it's something in the DRF, and I expect it's somewhere in the magic of how it interacts with the database rather than in the serializer, per se.

**Comment by pattisdr** [comment]
If I change date_created in the NodeSerializer, for example, from a DateTimeField to a CharField, the field type says `string` instead of `datetime`.  So it makes me feel like it's getting it from the serializer field type.

![screen shot 2015-08-25 at 3 17 24 pm](https://cloud.githubusercontent.com/assets/9755598/9476729/519f910a-4b3c-11e5-9d69-b737cf1be56a.png)

![screen shot 2015-08-25 at 3 17 50 pm](https://cloud.githubusercontent.com/assets/9755598/9476753/6cc2b534-4b3c-11e5-8a68-203e309f687c.png)

**Comment by pattisdr** [comment]
Under `rest_framework/metadata`, if you tamper with the label_lookup you can change the field types under OPTIONS.  This doesn't change what Swagger docs returns.  Notice that OPTIONS LinksField is `field

![screen shot 2015-08-26 at 4 09 05 pm](https://cloud.githubusercontent.com/assets/9755598/9504783/81c8c196-4c0c-11e5-96b3-09637c0cd117.png)

**Comment by brianjgeiger** [comment]
Good work. I would not be surprised to discover that django-rest-swagger has something similar then.

**Comment by pattisdr** [comment]
Oh yes, it's in `rest_framework_swagger/docgenerator.py`, method is `_get_serializer_fields`.  `links` doesn't match any of the scenarios described in the method for determining data_type, so it gets the default: `string`.

**Comment by brianjgeiger** [comment]
Does it look like something we can override without doing crazy things?
