### ISSUE TITLE
[production] User Unable to Reset Password in Safari

### ISSUE THREAD

**Issue by saradbowman** [CenterForOpenScience/osf.io#4038]
Steps
-------
1. User navigates to OSF using Safari and attempts to reset password
2. User inputs email address associated with OSF account and receives error message, "Not a valid email address."
3. User inputs a different email address, not associated with her OSF account, and receives a success message but no password reset email (expected behavior)
4. User clears cookies on Safari, tries again and experiences same behavior
5. User switches to Firefox to reset her OSF password, enters email address, receives success message and password reset email.

**Comment by lbanner** [comment]
@saradbowman Is this a single user issue? or a Safari issue that replicates? If single user, let's see what we can do to help them ... @sloria or @icereval ?

**Comment by saradbowman** [comment]
Single user reported - @Sloria investigated a bit, suggested a different browser. Using Firefox resolved the issue for this user.

**Comment by lbanner** [comment]
OK .... @caileyfitz or @jinluyuan ... can you test / aim to replicate in Safari, please? I'd like to make sure this is not a consistent user issue. Thanks.

**Comment by jinluyuan** [comment]
@lbanner I am unable to replicate in Safari (production). 

I still get a green success alert that the email has been sent to reset my password with all of these email addresses:
- my OSF account's email address
- an email address with special characters `{|}~` (not associated with any OSF account)
- an email address with a period `jinlu.yuan` (not associated with any OSF account)
- an email address with multiple periods in the domain (not associated with any OSF account)

When I input an email address with special foreign characters, like `á` and `í`, I get taken to the OSF's "Unable to Resolve" page.

The only kind of email address that gives an "Invalid" error is one with angled brackets `< >` in it. A red growl box error message appears since angled brackets are not valid email address characters, but the user can't have angled brackets in the email address.

**Comment by lbanner** [comment]
Thanks @jinluyuan -- I'll close this as a single case that has been resolved.
