### ISSUE TITLE
[API] Gravatar has hardcoded size

### ISSUE THREAD

**Issue by sloria** [CenterForOpenScience/osf.io#4051]
As an API user, I wouldn't expect any additional parameters to be added to the gravatar URL.

![django_rest_framework](https://cloud.githubusercontent.com/assets/2379650/9260988/1a9b0bba-41d9-11e5-9ed0-f129cf41e46e.png)

Requirements:
1) v2 serializer uses profile_image_url instead of gravatar_url because we may not always use gravatar;
2) modify the user view to accept a query parameter to set the profile_image_size.
3) By default, it will still return a specified size.

**Comment by brianjgeiger** [comment]
We had a brief discussion on this issue, and it's leading to the following proposed changes:
1) v2 serializer uses profile_image_url instead of gravatar_url because we may not always use gravatar;
2) modify the user view to accept a query parameter to set the profile_image_size.

By default, it will still return a specified size.

**Comment by sloria** [comment]
Perhaps we remove it altogether from the response model? After all, it is derived data--the client can compute the gravatar URL given the user's username.

**Comment by brianjgeiger** [comment]
No, you need an email address to get the gravatar, which we don't provide. We need an API method to get the url.

**Comment by sloria** [comment]
Oh ok, then including it in the response is fine.
