### ISSUE TITLE
When downloading a file with Script tags the file name is different

### ISSUE THREAD

**Issue by nicipfeiffer** [CenterForOpenScience/osf.io#4054]
Reported on the Markup Safe 3 board 
## Steps
1. Upload a file to OSF storage named `<script> alert('hello, world')</script>`
2. Click on the file name to go to the file detail page
3. Click the download button to download the file in your browser
4. Notice the file name and compare to the name entered on the OSF

## Expected
I would expect to see the same character in both places

## Actual
In the downloaded file the name is changed by the <> now being -s.

## Additional Steps

Also happens in the following case:

1. Rename a file in one of your add-ons (I tried Box)
2. Change title to `<i>QA is awesome!</i>`
3. Notice the change in the title upon refresh (see screenshot below)
![log_colon_character](https://cloud.githubusercontent.com/assets/9381062/9280813/f24a9476-428e-11e5-87df-3861a4b4a980.png)

The forward slash is changed to a colon.

## Comments
@lyndsysimon  - "The part where the filename upon download has dashes substituted for special characters is a separate concern, though. That's almost certainly happening in WaterButler."
and
"The display portion of this is correct - filenames on most systems cannot contain a forward slash. The weirdness is that OSX's Finder lets you name a file with a forward slash, but replaces it with a colon on the filesystem. If you open a terminal window and look at the filename, you'll see it's actually` <script>alert("hello, world")<:script>.txt`."

**Comment by chrisseto** [comment]
We can't do anything about this. Waterbutler sends back the correct content disposition, used to name the file, but it is up to the OS and Browser to give the file an actual name on disk.

![screen shot 2015-08-19 at 09 47 58](https://cloud.githubusercontent.com/assets/5532905/9357998/eabbd8ec-4657-11e5-964b-2e2f1abe946a.png)
Note the above decodes to `attachment; filename="<script> alert('hello, world')<:script>.png"; filename*=UTF-8''<script> alert('hello, world')<:script>.png`

@GaryKriebel this can be closed as this is expected behavior that we have no control about.
@nicipfeiffer I believe that you'll see the same behavior on other services.
