### ISSUE TITLE
Project descriptions field: cannot use > or < 

### ISSUE THREAD

**Issue by nicipfeiffer** [CenterForOpenScience/osf.io#4058]
Reported on the Markup Safe 3 board by @jinluyuan 

## Steps
1. Go a project on osf.io that you are an admin on
2. On the project overview page, click on the project description to edit
3. In the edit text field, enter `<ch&nge>`
4. Also enter, `&lt;&gt;&amp;` 
![screenshot 2015-08-14 09 53 31](https://cloud.githubusercontent.com/assets/9381062/9275327/5fddbbbe-426a-11e5-880f-afb5c4bf5b3b.png)

5. Save changes

## Expected
I would expect to see exactly what I type after save. #4 should show up as` <>&`

## Actual
#3 get escaped out entirely and #4 looks like ` &lt;&gt;&`
![screenshot 2015-08-14 09 54 11](https://cloud.githubusercontent.com/assets/9381062/9275338/71fc2ef2-426a-11e5-9ab6-0ce2f5d39dc7.png)

**Comment by abought** [comment]
#4 is the expected behavior: If you entered `&lt;&gt;&amp;`, then it should display as written. If it rendered differently (as `<>&`), that would indicate that the text you entered was being treated as code. We do not want that.

#3 is more problematic. In a local test, it wasn't "escaped" (rendered as inert text)- rather, the sanitizer removed the parts of your input that looked like HTML. Since that was all that was entered, the result was a blank description. This can be confirmed by adding more text outside the `<brackets>` and seeing that it is preserved after submission.

Pinging @jinluyuan to see if there's something I'm missing.

**Comment by jinluyuan** [comment]
## Clarification
[Trello card](https://trello.com/c/Fs5P5IEk/36-project-descriptions-field-edit-vs-display-show-different-text)

The original card described this issue like this:
>... [T]his issue with project descriptions only occurs on Staging. This issue also only involves the angled brackets `< >` and not the ampersand `&`

@nicipfeiffer's comment shows successful replication of the bug:
>I am able to replicate the bug where entering "<>&" in the project description and saving shows "&lt;&gt; &" on the project overview page in the description. It also appears that way on the search results page.

@abought's comment provides explanation to the behavior above
>Ah, the problem was only on the first instance of data entry? (rather than whenever you toggle between fields) I think that makes sense under the currently twisted definition of logic we are using.

>Because bleach instantly changes < to &lt; on save, the field now accurately represents what was saved in the database. (aside from the trickery we do to make ampersands look good)

>By contrast, on production, we get the exact opposite bug: sequences were being inserted in as code, so that typing &lt;&gt;&amp; and saving on production displays <>&.

## The problem
Essentially, the issue is that before this release, if a user inputted angled brackets (`<` and `>`) into the project description, the angled brackets would be displayed in the description. However, with the Markup Safe 3 feature, now the angled brackets are **not** displayed properly; instead they have escaped into `&lt; &gt;`.

This is a critical issue because angled brackets are common in science, specifically for math equations. For example, a user would not be able to include a statement like "the p-value < 0.05" in the description. 

This issue does *not* concern the ampersand `&` since it displays properly when inputted.

**Comment by abought** [comment]
The text is a literal depiction of how the data is stored in the database and will remain an issue so long as we use bleach in the current form as our sanitizer. That said, I do recognize that for abstracts, these symbols have value.

We have had problems in the past with `&lt;` and `&gt;` being unescaped in the display layer, so while we can special case ampersands, `<` and `>` are much trickier cases. Any change made here will need more thought and some care. Long term, the optimal fix would be to convert the entire OSF to markupsafe + deprecate/replace use of bleach (which is what is putting the escaped text into the database).

It might help to clarify the title to a single focused issue, such as "cannot use > or < in project description field".
