### ISSUE TITLE
Loophole for project contributor notifications

### ISSUE THREAD

**Issue by caileyfitz** [CenterForOpenScience/osf.io#4141]
I discovered a potential loophole for notifications when a user is added as a project contributor. Currently, if a user is added as a contributor to a project and then later added as a contributor to a component for that project, they will **not** get an email informing them that they have been added as a contributor to the component because they are already a contributor on the parent project. This exposes a way to circumvent the problem we were trying to solve: mainly that users could be added as contributors to projects without their knowledge. 

For example, suppose I have a project with the following structure:

***

#### Dynamos (component) 

***

Suppose the following take place:
1. I add Craig Biggio as a contributor to my project *Houston Sports Teams*  (Biggio **will** be notified by email)
2. I add Biggio as a contributor to *Astros*  (Biggio **will not** be notified by email)
3. Immediately after, I remove Biggio as a contributor from *Houston Sports Teams* (Biggio **will not** be notified by email of this action)
4. Biggio checks his email and sees that he has been added as a contributor to *Houston Sports Teams* and tries to access the project
5. Since I removed him, however, he will not have access and will instead just shrug his shoulders and figure the email was a fluke 
6. He will have **no** indication that he is a contributor to *Astros* other than perhaps noticing that *Astros* appears in his project organizer

I'm not sure what the best solution here is... Do we notify a user of their contributorship to a component upon being removed from the parent project? Or do we just assume that the chance that a user will attempt this is smaller than any benefit we may get from taking the time to come up with a solution to this? 

Pinging @samanehsan and @bnosek for any opinions

**Comment by bnosek** [comment]
Good issue to raise.  My perspective is that preventing this is not a
priority because it isn't easy to see use cases where the nefarious action
would be performed.  In addition, the component project will still show up
in the users dashboard, so they can discover it (like present
functionality) - they just aren't notified.

I do think that it will be worth adding notification for being removed from
a project, but that can be done as a later iterative step.  That would also
cue people to such misbehavior if it were ever to occur.  Logging remove
notifications as an issue for a future release would seem wise.

On Fri, Aug 21, 2015 at 8:28 AM, Cailey Fitzgerald <notifications@github.com

**Comment by caileyfitz** [comment]
:+1: @bnosek

**Comment by samanehsan** [comment]
I agree with Brian :+1:  In a later iteration, we might want to include links to the components in the email so that we do not rely on the user being able to see the components when they visit the project. But for now, since this seems like it isn't a common use case I think it does not need to be addressed immediately.
