### ISSUE TITLE
look for more fine grained permissions authorization

### ISSUE THREAD

**Issue by yarikoptic** [CenterForOpenScience/osf.io#568]
not sure if possible at all ATM, but here you go:
I really like to link OSF to my github account to operate on some public repositories.  But ATM I seems to need to grant OSF full control over my account:

```
 Repositories Public and private

This application will be able to read and write all public and private repo data. This includes the following:

    Code
    Issues
    Pull requests
    Wikis
    Settings
    Webhooks and services
    Deploy keys
```

I like and trust you guys, but that is a bit too much IMHO -- e.g. I would really like to not fix up a result of a possible code bug which would simply destroy all of my repositories.

**Comment by lyndsysimon** [comment]
Yarik:

We're in the process of re-organizing our list of issues, and after review, I don't believe this one is actionable at the moment.

I completely understand and appreciate your concerned - and for that matter, share it - but as Josh mentioned above we unfortunately have no way to address it right now. Because of this, I'm going to go ahead and close out this Issue.

One potential workaround for this would be to create a GitHub account specifically for sharing with the OSF and other applications, then give it access to only those repositories that you wish to connect. That's extra work on your end, of course, but it would absolutely ensure that third-party applications like the OSF wouldn't be able to modify things on your private GitHub account.
