### ISSUE TITLE
LDAP connection

### ISSUE THREAD

**Issue by sonnenschein123** [CenterForOpenScience/osf.io#5933]
Hello,
is it possible to connect the local osf to an local ldap server, so the user can log in with the same user data there using for all the other network applications.
Best 
Marius

**Comment by GaryKriebel** [comment]
@sloria?

**Comment by icereval** [comment]
We use Apereo CAS 4.1 for all authentication to the OSF. One would need to modify the cas-overlay's (https://github.com/CenterForOpenScience/cas-overlay) OSF Authentication module to interface with LDAP rather than the MongoDB backend. Further documentation on CAS and LDAP integration can be found here:  https://apereo.github.io/cas/4.1.x/index.html
