### ISSUE TITLE
[project-organizer] The "dashboard" folder at the top of the tree can be removed

### ISSUE THREAD

**Issue by bnosek** [CenterForOpenScience/osf.io#694]
And, then the other folders would slide left to be aligned with the left margin.

**Comment by brianjgeiger** [comment]
@bnosek Now that you've had some time to work with this, and now that we have the wider space for organizing, do you still think this is accurate?

**Comment by bnosek** [comment]
It certainly is not necessary considering that there are no other folders
at the same level.  The main arguments for retaining is if there will be
folders at the same level soon (even then, not essential now), or if there
is a UI advantage for having it (I don't see that easily, but perhaps).

**Comment by brianjgeiger** [comment]
The UI advantage is just that there's a specific drop target associated with dragging something into the dashboard. That's more of a development advantage than a UI advantage, I think. Right now, everything in the grid is based on rows, and by not having a row associated with the Dashboard folder, that means there has to be some other place to drag things. That space would be, generally, to the left of any row's icon and below all the rows. This is the area outlined in orange below:

![screen_shot_2015-03-12_at_3_34_50_pm](https://cloud.githubusercontent.com/assets/6599111/6626552/ec6c2870-c8cd-11e4-804d-6b4f8db06621.png)

Because everything's row-oriented right now, we would have to figure out a good way to make that area a drop target, which might be not the worst. Dragging something over that would cause the inside of the window to highlight, hopefully indicating that the drop target will be at the top level. Fairly standard insofaras.

I know with HGrid, just not showing the top row was indescribably difficult (mostly because I don't remember why, but it was fairly involved and specific to the Slickgrid/HGrid integration as I recall). I don't know if Treebeard will be easier to deal with that or not. I remember talking with @caneruguz about it several times, and I forget if the hold up was only the UI stuff above or if there was something similar to HGrid as far as the data structure went.

The question is more to determine if the request is a philosophical one to take the grid to its ideal state, or if it is causing difficulties because you are running out of space or similar. I know with the old grid, space was at a premium. The new UI allows us more room, though, so things may have slipped more to a philosophical issue.

**Comment by bnosek** [comment]
This looks like good rationale to leave as is.

**Comment by lbanner** [comment]
Thanks both -- maybe I won't close? Rather defer for now -- If close is better @brianjgeiger just let me know.

**Comment by bnosek** [comment]
You can close. If I ever have the gumption to try to face-off with
Notorious again, having to open a new issue will be a sanity check.

**Comment by bnosek** [comment]
You can close. If I ever have the gumption to try to face-off with
Notorious again, having to open a new issue will be a sanity check.

**Comment by brianjgeiger** [comment]
I don't mean to bully; if it weren't so hard, it definitely would have already been done. :smile:

**Comment by lbanner** [comment]
Cool :smiling_imp:
