### ISSUE TITLE
[production & staging] [User Profile] [Feature] Social Icons

### ISSUE THREAD

**Issue by kmjungersen** [CenterForOpenScience/osf.io#748]
As of right now, your social networks are simply displayed as links, and I think it would be better (and much more fun!) if there were icons for LinkedIn, github etc.  Just like on [COS.io](http://cos.io)

![screen shot 2014-07-18 at 4 57 23 pm](https://cloud.githubusercontent.com/assets/6546342/3631998/8006b44e-0ebe-11e4-8c22-006c1ab4bb5b.png)

**Comment by lyndsysimon** [comment]
Ping @rliebz for update?

**Comment by rliebz** [comment]
The code to implement this is essentially complete, but I did not have an open-source icon set to use. Assuming that part of the code base hasn't changed too dramatically, I could get a PR up relatively quickly if someone could direct me as to the best place to find icons that we are allowed to use.

**Comment by bnosek** [comment]
I don't know if any of these would be relevant:
https://google.github.io/material-design-icons/

**Comment by rliebz** [comment]
@bnosek It doesn't look like they have anything that specifically relates to those sites.

From Font Awesome, we do have access to Twitter, GitHub, LinkedIn, and Google (But not Google Scholar, specifically). On production, that would leave us without ORCID, ResearchID, and Impact Story. For the ones we don't have, we could do something somewhat generic (e.g., Font Awesome graduation cap for Google Scholar, if we didn't go with their logo), pretty generic (e.g., the letter "O" for ORCID), or really generic (a square with the same RGB values as their logo). We could also leave a blank space, if that's preferred.

**Comment by caneruguz** [comment]
I don't think anyone is working on this issue right now and it looks like it needs some clarification:

1. Font Awesome IS open source, we do use it on OSF - http://fortawesome.github.io/Font-Awesome/license/
2. Using another company's own gravatar seems legitimate from what I can tell (https://cyber.law.harvard.edu/metaschool/fisher/domain/tm.htm); however it's not super clear cut, especially since we make these open source. 
3. I think using logos is better than icons, some services we have don't have icons and using letter icons will potentially repeat certain letters. We want either all options have images or none. 

Based on the unclear status of the solution option I recommend we close this issue and consider instead the general question of "Can we use other logos legally in OSF?" which would include the question of the front page: 

![screen shot 2015-08-06 at 10 01 43 am](https://cloud.githubusercontent.com/assets/1314003/9113370/3bfc9498-3c22-11e5-9213-e7660083a4d6.png)

@nanchen47 @rliebz @JeffSpies @lbanner @GaryKriebel

**Comment by chennan47** [comment]
I agreed with @caneruguz . Related issues https://github.com/CenterForOpenScience/osf.io/issues/3867

**Comment by lbanner** [comment]
Ping @erinmayhood for consideration as inclusion on OSF Backlog. TY.

**Comment by JeffSpies** [comment]
We'd use the full logo in the space that the small icons are typically?

**Comment by caneruguz** [comment]
Icon size can be changed depending on the space available but the favicons on websites are often logos.  The use permissions would be the same. 

In terms of design the size of the displayed images would depend on location.

**Comment by JeffSpies** [comment]
Can we get a screenshot of where these would go?

**Comment by GaryKriebel** [comment]
@caneruguz, can I assume that you are referring to this:
![screen shot 2015-08-06 at 3 27 41 pm](https://cloud.githubusercontent.com/assets/9437946/9121360/c3880500-3c4f-11e5-976a-f0543f45c170.png)

Are you suggesting that we ONLY use:
![screen shot 2015-08-06 at 3 28 45 pm](https://cloud.githubusercontent.com/assets/9437946/9121371/dbdbd046-3c4f-11e5-982b-f7ed73f2c7cb.png)
on the line and no actual text?

**Comment by caneruguz** [comment]
Oh I see, yes let me clarify this a bit more. My conversation is originally in reference to the original issue of icons next to the services in Social tab of profile. The place Gary mentions is in the Add ons addition in settings pages and has a similar use case. In both cases there will be either BOTH images and text OR only text, never only image (except for the front page logos which should stay as they are).

Original Location in Social tab that I was referring to:
![6d7bf504-1342-11e4-8af6-8f2788e377d0](https://cloud.githubusercontent.com/assets/1314003/9121524/cb75597e-3c50-11e5-9c89-2153d508a02b.png)

Gary's screenshot shows the second location where the Add ons are selected in settings pages. 

Also I meant to say we use icons of services and social, **if their full logo is different than the icon then we use the icon**. In either case this is still their property so the permission needed to use them would be the same.  I didn't mean that we should use full logos only in these two locations.

**Comment by GaryKriebel** [comment]
You know ... I knew you were talking about that page, yet I focused on the
addon page anyway.

Though, I guess the same holds true for both.
