### ISSUE TITLE
Cannot link new GitHub org/repo to project

### ISSUE THREAD

**Issue by ctb** [CenterForOpenScience/osf.io#7811]
Hi all,

I'm trying to link https://github.com/osfclient/osfclient-test-integration/ to https://osf.io/fuqsk/, but can't seem to see that project/repo on the pull down list.  Actually, it may be there, but since I have well over 100 github repos, it's hard to find on the list - which is not sorted in any obvious way (see attached image).

So really this is kind of two issues - first, I can't figure out how to refresh my list of github repos, and second, the list of repos is not sorted in a predictable or obvious way.

Suggestions welcome!

--titus

<img width="283" alt="screen shot 2017-10-15 at 8 31 57 am" src="https://user-images.githubusercontent.com/51016/31586267-67166bb2-b183-11e7-98e3-6668b53111c4.png">

**Comment by brianjgeiger** [comment]
There's an embarrassingly old issue that will be fixed in the next… month or so that allows you to see organizational github repos. That may solve the main problems. One of the aspects of this is upgrading the github client that we're using, and that may also help with the sorting (but it might not). Agreed that filtering would probably help here, as well as a sane sort order if the github client supports such a thing.

**Comment by brianjgeiger** [comment]
@ctb I think we've figured out the problem. Did you generate the OAuth token for the OSF before you had the osfclient Organization? Github requires you to explicitly request access for organizations when you generate the token, so new orgs won't come through on that token. If you clear out your old token and add a new one, that should fix the problem. 

Now that we know about this, we may have to work on the interface a bit to make it easier to deal with this situation.

**Comment by BRosenblatt** [comment]
@ctb were you able to connect your org to your OSF project re @brianjgeiger's advice?

**Comment by ctb** [comment]
Yes, revoking the token and then granting access worked!! thank you!
