### ISSUE TITLE
Fix layout for very long strings in user profile

### ISSUE THREAD

**Issue by XTech2K** [CenterForOpenScience/osf.io#836]
Right now, the personal fields on profile pages (and likely in other places) seem to have character limits that are either nonexistent or large enough to seem so. As displayed below, this can lead to some of our pages looking less-than-ideal if someone fills a field in with an overtly-long response.

![screen shot 2014-08-05 at 11 16 08 am](https://cloud.githubusercontent.com/assets/5955359/3813461/7cfe01c8-1cb3-11e4-873c-5aeb790f1e02.png)

This also makes it harder when we want to use this information on other parts of the site, such as in contributor searches and the such.

**Comment by haoyuchen1992** [comment]
Firstly, I agree with Lyndsy's point that it is unnecessary to set the maximum length here.  And also the reason why it is out of boundary is because the input is a very long word. In default setting, that word will not be break and also its length will be the width of the table cell (td).

However, in our real use case, it is nearly impossible to have such a long single word. The most complicated one may be just as the same as Lyndsy pointed out. Below is the screen shot when it shows in our table.
![screen shot 2015-06-25 at 4 07 44 pm](https://cloud.githubusercontent.com/assets/5420789/8364473/9ed630a4-1b54-11e5-8c85-585d69a5c0e4.png)

As we can see, the width is dependent on the longest word here. Our current implementation totally meets the needs in real usage setting. Therefore, I suggest that we could close this issue.

**Comment by caneruguz** [comment]
@lbanner This will be fixed with 0.45, on staging you can see that the table cells already break the long words:

![screen shot 2015-08-06 at 9 48 23 am](https://cloud.githubusercontent.com/assets/1314003/9113057/69af47ac-3c20-11e5-891b-6252c0bdda01.png)

**Comment by lbanner** [comment]
OK .... any particular PR?

**Comment by haoyuchen1992** [comment]
@lbanner This one -- https://github.com/CenterForOpenScience/osf.io/pull/3952

**Comment by lbanner** [comment]
Thanks

**Comment by nanchen47** [comment]
This pr has been merged and deployed on production.
