### ISSUE TITLE
Version/download info table overlaps with rendered PDFs

### ISSUE THREAD

**Issue by samanehsan** [CenterForOpenScience/osf.io#873]
When rendering PDF files, the table on the right overlaps with the document even at max screen width (viewing on 13" macbook). 
![screen shot 2014-08-22 at 11 30 10 am](https://cloud.githubusercontent.com/assets/6414394/4013670/acd36588-2a18-11e4-8436-d2edc55500fb.png)

This does not happen when rendering word documents-- the text narrows to accommodate the table as you change the screen width.  
![screen shot 2014-08-22 at 11 30 58 am](https://cloud.githubusercontent.com/assets/6414394/4013744/84592204-2a19-11e4-8c80-e5e2ed936ee7.png)

**Comment by caileyfitz** [comment]
@sloria @caseyrollins @samanehsan  I know this issue is closed, but I found something similar to be happening on production now with a word file I have uploaded. See image below: 
![screen shot 2015-01-27 at 10 33 54 am](https://cloud.githubusercontent.com/assets/5975444/5921185/3b5291a8-a610-11e4-9f1b-d3aabbe2f5f3.png)

Should I create a new issue for this? Or should we re-open this issue?

**Comment by samanehsan** [comment]
@caileyfitz, go ahead and create a new issue for this one since it's specific to word files, not PDFs. Thanks!

**Comment by brianjgeiger** [comment]
I suspect it's a genuinely new issue. I'd make a new one.

**Comment by brianjgeiger** [comment]
+1 to @samanehsan :)

**Comment by caileyfitz** [comment]
Alright I'm about to create a new issue!
