### ISSUE TITLE
[feature request] keep "View Registration Form" for embargoed registrations

### ISSUE THREAD

**Issue by petyaracz** [CenterForOpenScience/osf.io#8774]
Steps
-------
1. Go to my dashboard
2. Click on my project

Expected / requested
------------

1. See a "View registration form" button even if the registration has been filed.
2. Have a note saying that the form cannot be edited anymore as it has been embargoed by user x at date n.

Actual
--------

The button goes away once the form is embargoed. You can get to your registration by
1. Not clicking on a project on the dashboard
2. Going to my projects instead
3. Clicking on my registrations

**Comment by BRosenblatt** [comment]
Thank you for this feedback, @petyaracz. We keep an internal tracker of feature requests and feedback from our users that we use to help inform future development, and I'll add your feedback to the list.

To address the "Expected behavior," registrations aren't currently indexed on the user dashboard. To navigate to a registration from your dashboard, you would need to open the project that you registered first, click the **Registrations** tab in the navbar, then open the registration from this page.
