### ISSUE TITLE
Inconsistencies in how sanitization is handled

### ISSUE THREAD

**Issue by rliebz** [CenterForOpenScience/osf.io#946]
If the user's fullname is changed from their profile page, script tags appear to be escaped as HTML characters. For example, `<script>console.log('Robert')</script>` becomes `&lt;script&gt;console.log('Robert')&lt;/script&gt;`.

If the user's fullname is instead changed from their settings page, script tags are removed completely, leaving `console.log('Robert')`.

It is important to note that CenterForOpenScience/osf/pull/812 likely resolves this specific issue, but these multiple methods of sanitization are still both actively used. For example, renaming a project from the project's dashboard follows the pattern of the first, while renaming from the new project organizer follows the second. 

Do we/should we have a standard for sanitization?

**Comment by lyndsysimon** [comment]
Dropping back to "working" status, and this is now planned for 0.24

We've had a lot of broad changes go in over the past few weeks, and after discussing with @lbanner and @GaryKriebel, the best course of action here seems to be to defer until 0.23 is live, and re-implement this change instead of trying to merge. So many files have been moved, renamed, and refactored, attempting to reconcile the differences is taking longer than starting fresh.

**Comment by lbanner** [comment]
Agreed - Thanks

**Comment by GaryKriebel** [comment]
I concur... either a .23-dot release or push into .24 release

**Comment by brianjgeiger** [comment]
This is fixed for Ampersands, but only partially fixed for < and >.

![screen shot 2015-03-18 at 1 50 49 pm](https://cloud.githubusercontent.com/assets/6599111/6715593/ecb88128-cd75-11e4-83d4-aac989666b17.png)
![screen shot 2015-03-18 at 1 50 38 pm](https://cloud.githubusercontent.com/assets/6599111/6715592/ecb4d37a-cd75-11e4-9f83-db685d5631a6.png)

**Comment by lyndsysimon** [comment]
My PR above never got merged; Andy is now working on this.

**Comment by abought** [comment]
New tracking issue: #2933

**Comment by lbanner** [comment]
Got it -- Thanks.

**Comment by nanchen47** [comment]
Close this one and continue tracking on #2933
