### ISSUE TITLE
[staging] Dialog box for adding new contributor to project's children

### ISSUE THREAD

**Issue by csheldonhess** [CenterForOpenScience/osf.io#950]
I have a project that has two components to it. Both components are shared with a contributor (in the screenshot below, ParodyBit), but the parent project was not shared with her. 

After I added the contributor to the parent project, the dialog box still came up, offering me the opportunity to add that contributor to either/both of the components, even though she is already a visible, read/write contributor to both of them. 

Screenshot:

![image](https://cloud.githubusercontent.com/assets/3027971/4324217/0c127936-3f58-11e4-9a80-9171343847fb.png)

**Comment by caileyfitz** [comment]
Just ran across this issue again. User "brownie sundae" is already a contributor on *Corn or Flour*, but it does not appear so in the modal. 
![screen shot 2015-05-06 at 2 35 49 pm](https://cloud.githubusercontent.com/assets/5975444/7500689/36f87ea2-f3fd-11e4-95f8-028a35d3d8a2.png)

Still confusing and it appears as though @kushG has a pending fix for this from months ago. Trying to revive this so that we can get it resolved, as I do think it is something that users may encounter frequently
